### ISSUE TITLE
Mobs With Shaders Cannot See Menu Elements

### ISSUE THREAD

**Issue by mario384** [Ladysnake/Requiem#106]
While not currently possible to access when playing this mod with vanilla mobs, any mob which has a shader vision prevents the player possessing it from seeing things like the escape menu, inventory, or chat bar.

**Comment by sschr15** [comment]
*Almost an entire year later*
I (partially) fixed it! It is available at the [Legacy Dissolution](https://github.com/Ladysnake/Dissolution-Legacy) repository or at the latest 1.12 file uploaded on [CurseForge](https://curseforge.com/minecraft/mc-mods/Requiem). Thanks for reporting this bug even if there was no support for this mod for nearly a year!
