### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by Alrena** [Ladysnake/Requiem#111]
Millenaire,  Rough Mobs 2, and Electroblob's Wizardry all have strange issues with Dissolution.

Millenaire has towers in which traders reside. While a skeleton I attempted to open one of the locked chests and this immediately happened. https://i.imgur.com/q3LDp97.png
Exiting the world and reloading it fixed the issue, but it immediately happened again upon clicking to open the chest.

Electroblob's Wizardry has an Ice Statue spell which freezes your body and puts you into stasis. Dissolution takes this as you dying and kicks you to the spirit world. Attempting to enter another mob during the spell duration also immediately freezes the second mob body and kicks you to spirit form again. Should you enter multiple bodies during this spell effect you suddenly inhabit all bodies posessed, including your original, upon the end of the spell effect. The multiple bodies attack each other when a weapon is swung.

Rough Mobs 2 introduces mobs with much higher health than normal, including some named boss mobs. These mobs can be possessed, granting you the much higher health pool (I had a skeleton body with 40 health). Additionally when you revert back to human from inside a very high health mob you keep that max health as a human.

As a side note, is it possible to get a config option to manually add mobs to possess? I wanted to enable possessing vampires from the Vampires mod and maybe some of the enemies from Grimoire of Gaia or other undead mobs.

**Comment by Pyrofab** [comment]
The issue with keeping health after possession stops is fixed in Requiem. The other mods are not available in supported versions, so I'll close this.
