### ISSUE TITLE
Lag spike when looking at player shells in offline mode

### ISSUE THREAD

**Issue by Pyrofab** [Ladysnake/Requiem#113]
From #112 :

"Each time the shell is created client-side it seems to send an authorization request, presumably to get the player skin. Tbh I haven't dealt with player skins yet, but I do know that this does not happen when an actual _player_ comes into/leaves view repeatedly, so there must be some other way to get the skin on there without all the requests.

In fact, I don't think the client even sends any requests at all for normal player entities; I think the skin might be passed from the server or something...not sure though.

In any case, the result is that the service quickly starts rejecting the requests due to frequency, at which point the skins fail to load and the game starts getting lag spikes upon each failed request (either main or render thread must be freezing until skin either loads or fails to load)."

**Comment by Laike-Endaril** [comment]
You're right, this only seems to happen in offline mode.  I thought I was in online mode when I encountered it, but that doesn't seem to be the case.

I could not reproduce the lag spikes even when repeatedly making shells flash in and out of existence client-side by spinning around with dynamic stealth installed, so this is not nearly as big an issue as I first thought (except for someone running an offline server).

**Comment by Pyrofab** [comment]
No more shells in Requiem, no more issues. I still fixed this bug for... reasons.
