### ISSUE TITLE
Suggestion: Compatibility with Robotic Parts mod

### ISSUE THREAD

**Issue by Sparksolur** [Ladysnake/Requiem#114]
It's pretty niche interaction, but since in that mod you can remove organs or flesh to replace them with mechanical bits, those could be another source for human flesh and organs.

**Comment by Pyrofab** [comment]
Maybe. Right now we are focusing on rewriting the mod for future versions / less bugs / better gameplay, so mod compatibility is pretty low on the list. Although to be honest the author of Robotic Parts could just as easily give those items on their own terms.

**Comment by Pyrofab** [comment]
Robotic Parts is no longer on a supported version, so I'll close this.
