### ISSUE TITLE
Unusual interaction with RFPR

### ISSUE THREAD

**Issue by Derpford** [Ladysnake/Requiem#115]
When the Real First Person Render mod is installed, upon dying with a Remnant Soul, the player's screen goes white. This only occurs while HUD elements are being rendered; if you press F1 to disable HUD elements, the rendering issue disappears. As noted in [this comment](https://github.com/DonBruce64/RealFirstPersonRender/issues/14#issuecomment-468060920), it's possible this is caused by the transparency effect on the ghost player, and this could be better solved if the Dissolution team works with the RFPR team.

**Comment by Pyrofab** [comment]
Well, this issue still exists with the Fabric equivalent of RFPR...

**Comment by Pyrofab** [comment]
Actually that issue doesn't exist anymore it seems, so I guess you can update to 1.16 if you want a fix =3
