### ISSUE TITLE
Being undead won't work

### ISSUE THREAD

**Issue by Gmoinit** [Ladysnake/Requiem#116]
When I choose a host for the spirit, the screen freezes an stays like that the whole time, I can hear myself moving and breaking blocks but it just shows me what it looked like before I "possessed" it
![Screenshot (2152)](https://user-images.githubusercontent.com/48418843/54091594-c1897800-434f-11e9-9526-6260faf1aba3.png)
It just looks like this whatever I do

**Comment by Pyrofab** [comment]
Could I maybe get a log of a game session where this happens (see `logs/latest.log` in your minecraft instance) ? This is likely to be an incompatibility between mods as well.

**Comment by Gmoinit** [comment]
[latest.log](https://github.com/Ladysnake/Dissolution/files/2950149/latest.log)

**Comment by Pyrofab** [comment]
This appears to have something to do with Mo Creatures failing to render a werewolf. Not sure I can do anything.
