### ISSUE TITLE
Night vision for ghosts

### ISSUE THREAD

**Issue by deadspidervenom** [Ladysnake/Requiem#117]
When using CMDCam if you possess a mob the camera is tilted until your a human again or die.

Also idk if this is a incompatibility or a feature, But hostile mobs seem to follow me when i possess a undead mob. i have zombie awareness and dynamic stealth, i thought it might be them but i am not sure.

**Comment by Pyrofab** [comment]
Normally the only mobs that should target you are the natural predators of the creature you possessed. I do think zombie awareness is causing issues there.

**Comment by deadspidervenom** [comment]
Their not really targeting though, just following it seems. Though after testing some stuff out with Dynamic Stealth it seems you are right and its caused by a incompatibility with Zombie Awareness.

**Comment by Pyrofab** [comment]
What I think is happening is Zombie Awareness ignores the invisibility and invicibility of your player and goes after it, but can't hurt it for obvious reasons.

**Comment by deadspidervenom** [comment]
Will confirm its zombie awareness. just removed it, they stopped following.

On a side note could i recommend giving ghosts night vision and possibly spectator like passing through walls? if you die during the day above ground, you get stuck till night unless you find a cave. and if you are using a hardcore darkness mod or dynamic stealth, you can't find mobs inside of caves because of either darkness or natural stealth.

**Comment by Pyrofab** [comment]
Ghosts have night vision since 1.4.0, and they can go through walls ! Took me long enough...
