### ISSUE TITLE
Corosus' Zombie Players mod incompability

### ISSUE THREAD

**Issue by MMMiracles** [Ladysnake/Requiem#121]
[Mod Link](https://minecraft.curseforge.com/projects/zombie-players) occurred on _zombie_players-1.12.1-1.2.7.jar_

2 main things:
- Whatever method used for the mob's texture gets corrupted when possessing the zombie player mob, it looks more like when a wrong texture is applied to something.
- Shortly after possessing the mob the game will crash with a nullpointer exception while saving the NBT entity data.

[crash-2019-04-20_22.22.42-server.txt](https://github.com/Ladysnake/Dissolution/files/3100893/crash-2019-04-20_22.22.42-server.txt)

**Comment by Pyrofab** [comment]
Probably fixed in Requiem, although Zombie Players is not available to test.
