### ISSUE TITLE
[1.12] Incompatibility with shaders.

### ISSUE THREAD

**Issue by Akayen02** [Ladysnake/Requiem#122]
Loading world with Dissolution and Optifine shaderpack (BSL V7.1 or SEUS Renewed) causes the screen to be stuck at the image of loading screen ("dirt screen") or, if shader is enabled after world was loaded, at the image of shader's menu.
The Dissolution's shader disable option doesn't help.
Is there a way to fix this?

**Comment by Legendary4226** [comment]
It's same for me !

**Comment by Pyrofab** [comment]
Someone on the discord found how to fix it, you can disable shaders before entering the world and re-enable them afterwards.

**Comment by NAKothana** [comment]
That doesn't work, because then the game just gets stuck on the shader selection menu.

**Comment by 16-squared** [comment]
The description says that this mod is not compatible with OptiFine

**Comment by Pyrofab** [comment]
True, I think it's about time we close this issue.
