### ISSUE TITLE
Undead players are sometimes rendered twice

### ISSUE THREAD

**Issue by doctor4t** [Ladysnake/Requiem#126]

**Comment by ChicheCapitalist** [comment]
Yep, this happens sometimes, its very bad because when playing with friends then can see it bugged.

**Comment by fatlard1993** [comment]
I see this quite often, sometimes its the normal player inside the undead mob or even the last undead mob inside the new undead mob.

**Comment by vrnRaptor** [comment]
Same problem when playing with friends.

**Comment by Pyrofab** [comment]
I believe this should now be fixed in 1.16, feel free to reopen if it isn't.
