### ISSUE TITLE
After installing Requiem and playing, restarting Minecraft causes a NPE

### ISSUE THREAD

**Issue by doctor4t** [Ladysnake/Requiem#130]
[crash-2019-05-30_14.50.37-client.txt](https://github.com/Ladysnake/Requiem/files/3237072/crash-2019-05-30_14.50.37-client.txt)

It seems that deleting Requiem in the mod folder and reinstalling it fixes the issue. Installing satin as a stand-alone breaks every shader and is not a viable fix.

**Comment by Pyrofab** [comment]
Fixed in pre8
