### ISSUE TITLE
OpenGL Error: 1281 (Invalid Value) / 1282 (Invalid Operation) occurs when Optifine has Fast Render enabled

### ISSUE THREAD

**Issue by Jivvy** [Ladysnake/Requiem#137]
Once you're in demon bodiless mode, your game completely freezes when Fast Render is on.
I know that Fast Render is incompatible with shaders, so I suspect this is 100% Optifine's fault, but maybe you could add this incompatibility in a few locations. Just thought I should report it in case it's something you can fix. Not much more to say. 

requiem 1.0.0-pre9

**Comment by Pyrofab** [comment]
Fast Render is notorious for breaking modded renders, so I don't think I will try too hard to fix it. But you are right, it should be noted in some places.
