### ISSUE TITLE
Small Tweak: Remove spacebar capability when in demon mode

### ISSUE THREAD

**Issue by jivvy** [Ladysnake/Requiem#138]
When the player doesn't have a body, they get a modified form of creative flight. Decreasing the player's vertical maneuverability could discourage the player from flying around at high altitudes.
Just figured I could inform you about this option. No pushiness :)

**Comment by Pyrofab** [comment]
I don't think I understand exactly what you are suggesting. How are you supposed to fly upwards without spacebar ?

**Comment by Jivvy** [comment]
You can actually look up and hold W and you slowly ascend. I was surprised by this too. Must be a residual of putting the player into swim mode?

**Comment by Pyrofab** [comment]
Oh, right, that. Not sure how I would feel about that, it would require permanent swim mode which would decrease mobility by quite a bit.
