### ISSUE TITLE
Suggestion: Server-Wide Setting

### ISSUE THREAD

**Issue by Zeklo** [Ladysnake/Requiem#139]
It would be handy to be able to enforce all players to be a demon through a config option or the like. No choice on first death. No Opus Daemonium. Just flat out, always a demon no matter what.

**Comment by Pyrofab** [comment]
A gamerule for example ?

**Comment by Zeklo** [comment]
A gamerule would absolutely work.

**Comment by Pyrofab** [comment]
I am thinking such a gamerule would specifically determine the initial state for new players. Operators can always use commands to change a specific player's status, and it is easy enough to disable the recipe for the Opus Daemonium.
