### ISSUE TITLE
Suggestion: Gradual Cure

### ISSUE THREAD

**Issue by Zeklo** [Ladysnake/Requiem#140]
Currently recovering your humanity is instantaneous. It would be neat if this was more akin to villager curing and took a couple minutes to take effect. Probably good for a config option to allow increased or no delay whatsoever.

**Comment by Pyrofab** [comment]
Is there any reason for that ? If you have all the things to convert, why have to wait ?

**Comment by Zeklo** [comment]
Mostly for thematic purposes, but also to leave somewhat of a buffer for players who have managed to stock up on the materials required for resurrection. So they aren't immediately overcoming the consequence of death.
