### ISSUE TITLE
Suggestion: Husk Drowning Transformation

### ISSUE THREAD

**Issue by aaronliu0130** [Ladysnake/Requiem#142]
I might be wrong here because I have not become a demon yet, but, as of Minecraft 1.13, when a husk stays down in the water for too long, the husk turns into a zombie, which, if still stays there for too long, will still turn into a drowned.
So, would you kindly make a possessed husk transform into a zombie if it stays in the water for too long?

**Comment by Pyrofab** [comment]
This behaviour, like most passive behaviours, is indeed supported by Requiem. I therefore invite you to try it yourself =)
