### ISSUE TITLE
Suggestion: Helmets should not take damage in the sun when equipped by an undead mob with fire resist

### ISSUE THREAD

**Issue by Birgliss** [Ladysnake/Requiem#143]
this would include zombies with fire resistance, but more specifically undead mobs who have this innately
such as wither skeletons, zombie pigmen, etc

**Comment by Pyrofab** [comment]
Blame Mojang, I am running the vanilla behaviour exactly.

**Comment by Birgliss** [comment]
yeah. i figured that out once i realized standing on a boat would make you sit in it, lol

bit of a bummer but understandable
