### ISSUE TITLE
Requiem 1.0.0 and Immersive Portals 0.19 Bug

### ISSUE THREAD

**Issue by Kamalalshair** [Ladysnake/Requiem#144]
I have not tested this on every mob, but with skeletons, when the portal renders, it renders the head of the Skeleton in first person mode which covers the camera.

**Comment by Pyrofab** [comment]
Indeed, Immersive Portals breaks possession in all sorts of ways. Don't try to go through a portal as an undead either.
I will try to fix those incompatibilities, but IP works in mysterious ways.
