### ISSUE TITLE
[suggestion] Corpse mod Integration

### ISSUE THREAD

**Issue by TheSexyYeti** [Ladysnake/Requiem#145]
You should integrate this mod with Henkelmax's Corpse mod. So when you return to where you died. You can simply click on the corpse and re-inhabit your body and come back to life. But if the you take too long to get back to the corpse and it has decayed into a skeleton. Then you can't re-inhabit it. And you would be forced to possess a mob and come back the other way.

**Comment by Pyrofab** [comment]
It appears the mod you are suggesting is for Forge. If it is not for Fabric, it will be difficult to add compatibility for it in the near future.

**Comment by yuno44907** [comment]
What is fabric and why not forge?

**Comment by Pyrofab** [comment]
Fabric is an alternative modding toolchain made by the community. It is generally more permissive than Forge, which is very much welcome when working on a mod like Requiem.
More answers [here](https://www.curseforge.com/minecraft/mc-mods/requiem?comment=358)

**Comment by yuno44907** [comment]
Is it possible to use fabric and forge together by putting their mods in different folders or this requires to edit launcher?

**Comment by lag42** [comment]
i know i'm a month late, but is there any way i can keep an eye on this project? it's nothing i've heard of or can find

**Comment by Pyrofab** [comment]
You would keep an eye on this organization: https://github.com/PatchworkMC
