### ISSUE TITLE
[Question] Whitelist Config File

### ISSUE THREAD

**Issue by NINJAGAMER4227** [Ladysnake/Requiem#146]
So, I've played with the mod for a couple days now, and I've done pretty much everything there is to do. Is there a config file I can edit to add mobs to possess? Sort of a "whitelist" of mobs that are possessable?

**Comment by Pyrofab** [comment]
We intend on allowing every mob to be possessed in the future, but we have not decided on the mechanics that will balance it. As such, we would rather wait before adding such a config option.
Note that the opposite is possible, there is a blacklist [tag](https://minecraft.gamepedia.com/Tag) that can be updated by data packs.

**Comment by NINJAGAMER4227** [comment]
Alright, thanks! As for the mechanic, how about a sort of "battle of wills" in which you have to upgrade your soul/will before you can win. If you have a stronger will/soul, you can force the soul of the mob out, devour it, then possess it. If you have a weaker soul, then you lose some of your soul strength and the mob gets buffed for several minutes.

**Comment by NINJAGAMER4227** [comment]
To upgrade your soul enough to devour your first mob, maybe you have to eat a "spirit fruit" or something. Or maybe you have to meditate (build up to, say, layer 255, then sit there from sunrise to sunset), or even just exist for long enough?

**Comment by Pyrofab** [comment]
That is indeed the general idea, but how to make it interesting ? Should it just be a hard "will power" number on each side that makes you win or lose, or a random chance of possessing that gets better the stronger you are, or a minigame, or an actual ghost fight ?

**Comment by NINJAGAMER4227** [comment]
It should be a random chance that gets higher each time you level up your soul. A minigame should be an EXTREMELY small chance that gets higher each time your soul levels up (but stays the same relative chance).  Just possessing it will require you have at least 3 levels of soul above the thing you're trying to possess, and if your at max, you have the option to reset and make it 1 level, then when you're at max again you reset again to make it same level. An actual fight between the ghost and you should be somewhere around 50%-60%, and just possessing it should be 40%-50%.

**Comment by NINJAGAMER4227** [comment]
As for the minigames, just have it short and sweet, i.e. a race, a pvp fight in which the ghost and you are armored (just make the opponent a player skin of that mob, i.e. a player with the username "Pig" has a pig skin)

**Comment by Pyrofab** [comment]
Well, in recent requiem versions you can install an addon to possess every entity. We also have some ideas for a possible progression system, so I'll consider this issue closed. Thanks for the ideas !
