### ISSUE TITLE
readme wrong links?

### ISSUE THREAD

**Issue by inspire22** [Ladysnake/Requiem#151]
The setup section links to https://minecraft.curseforge.com/projects/requiem

Clicking download downloads "Dissolution-1.12.2-0.3.9" - which then says it's the beta forge version and new development is happening on fabric.  How do I download the fabric version?  I'm using MultiMC

**Comment by inspire22** [comment]
Aah, I needed to click the "Files" tab and download the proper version.  The "Download" link that curseforge puts in the top right corner seems to be nearly always wrong....

**Comment by Pyrofab** [comment]
Ah yes, curseforge being garbage as usual. Glad you found it !
