### ISSUE TITLE
Compat Issue  Shulker Charm

### ISSUE THREAD

**Issue by MLMII** [Ladysnake/Requiem#156]
Just wanted to report an issue with Requiem, with Shulker Charm installed you lose the ability to fly while in "spirit form" after dying but before finding an undead host.
 
Thank you for your time,
 
https://www.curseforge.com/minecraft/mc-mods/shulker-charm

**Comment by martmists** [comment]
To fix this, PlayerAbilityLib could be used.

**Comment by Pyrofab** [comment]
Some say PlayerAbilityLib was created exactly for that reason
