### ISSUE TITLE
Taking damage as undead does not affect health bar visibly

### ISSUE THREAD

**Issue by martmists** [Ladysnake/Requiem#167]

**Comment by Pyrofab** [comment]
Now that's unexpected. Does it happen all the time ? Keep in mind zombies always have some armor.

**Comment by martmists** [comment]
Happens consistently, affects both Wither Skeletons and MobZ:Tank so far. Possibly an incompatibility with HealthOverlay, but unlikely.

**Comment by Pyrofab** [comment]
Actually yes, an incompatibility with HealthOverlay

**Comment by martmists** [comment]
Latest version: Health display does not function with mobs that have more than 20 health when using healthoverlay
