### ISSUE TITLE
Incompatible with Immersive Portals

### ISSUE THREAD

**Issue by fatlard1993** [Ladysnake/Requiem#170]
https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod

**Comment by Pyrofab** [comment]
https://github.com/Ladysnake/Requiem#mod-interactions

**Comment by fatlard1993** [comment]
Thank you.

**Comment by Pyrofab** [comment]
FYI, compatibility with immersive portals has been achieved on 1.14, but 1.15 broke everything again. It will probably come back eventually.

**Comment by Pyrofab** [comment]
https://github.com/qouteall/ImmersivePortalsMod/commit/f9986799c2ece3c916045a4f5be1c12506a88e31#diff-4faa68b0fda7fa604be755936bb003f9
seems like it should be soon get a proper fix.
