### ISSUE TITLE
Demons Look Like Normal Players

### ISSUE THREAD

**Issue by IndieanaJones** [Ladysnake/Requiem#177]
What it says on the tin, players on the current version appear normally if they're a demon in soul form.

**Comment by Pyrofab** [comment]
Known issue in 1.15, I have to reimplement it on top of Minecraft's new rendering (blaze3d)

**Comment by Pyrofab** [comment]
Oh hey, it's fixed now ! The old effects were re-implemented during the 1.16 port.
