### ISSUE TITLE
Server Crash upon joining

### ISSUE THREAD

**Issue by Zaygh** [Ladysnake/Requiem#181]
While possessing a Zombie the server closes unexpectedly and upon trying to rejoin it just crashes. Crash report here:

https://pastebin.com/5ELnsb61

Not sure if it specifically matters it was a Zombie.

**Comment by Pyrofab** [comment]
I don't think it was about the possession, more about the body you left behind. I'm not too sure what happened, will have to investigate.

**Comment by Pyrofab** [comment]
Considering how player shells have been reworked in the last few versions, I'll assume this crash is no longer relevant. Feel free to reopen if you get it again.
