### ISSUE TITLE
Unable to sleep when not in human form

### ISSUE THREAD

**Issue by James103** [Ladysnake/Requiem#185]
In Requiem 1.1.4 in Minecraft 1.15.2, you are unable to sleep when not in human form. Attempting to sleep anyway throws the following error:
> You may not rest now, there are monsters nearby

This applies even if you are the only entity in the world.

If this is intended, then that should be noted under "All undead players" in README.md.

**Comment by Pyrofab** [comment]
Right. Yeah this is pretty much intended, although I guess we should customize the error message.

**Comment by James103** [comment]
Something like "You may not rest now, you **are** a monster"?

**Comment by IdrisQe** [comment]
Adding to this, it would be nice if this behaviour could be disabled somehow.
Using things like the hammock in Comforts, or the Coffin in Bewitchment, allowing you to sleep through the day would be invaluable for when you're possessing mobs that... sunburn easily. Obviously this affects balance somewhat... But only if you intentionally use both mods together, in which case this functionality (the coffin in particular) only feels natural.

**Comment by Pyrofab** [comment]
Fixed in 2.0.0 alphas ☑
