### ISSUE TITLE
Pandemonium seems to crash the game

### ISSUE THREAD

**Issue by mariotime1287** [Ladysnake/Requiem#190]
On MC 1.16.3, using Pandemonium 1.2.0 and Requiem 1.2.0 on fabric-loader-0.10.0+build.208-1.16.3 causes a "Joining World..., Saving World" crash, with exitcode -1. I haven't tried any other fabric versions, and it's only with Pandemonium on that the crash occurs. Without it, the game functions as intended. I only have Requiem and Pandemonium on. 
Full crash report down below:
[crash-2020-10-04_21.33.00-client.txt](https://github.com/Ladysnake/Requiem/files/5324807/crash-2020-10-04_21.33.00-client.txt)

I hope that if this isn't an issue on my end, that it is simple to fix.

**Comment by Pyrofab** [comment]
Yup, it's our fault. Pandemonium should be updated soon.
