### ISSUE TITLE
[1.16.3] Crash Upon Load

### ISSUE THREAD

**Issue by cybercat5555** [Ladysnake/Requiem#194]
When trying to load Requiem 1.2.2 on fabric 0.10.2+build.210 with fabric api 0.25.0 build 415 I got this crash: 
[crash-2020-11-09_10.31.20-client.txt](https://github.com/Ladysnake/Requiem/files/5511537/crash-2020-11-09_10.31.20-client.txt)

Not sure what's happening, or if I forgot to do something simple like not include a dependency, but nothing about that was mentioned

**Comment by Pyrofab** [comment]
I believe this is because of an old version of Fabric API. Could you try with the latest one ?

**Comment by Pyrofab** [comment]
Assuming fixed with latest Fabric API
