### ISSUE TITLE
No Mob Drops

### ISSUE THREAD

**Issue by ravensniper72** [Ladysnake/Requiem#195]
This happens in the 1.16.4 version. When I am possessing a mob I am unable to get mobs to drop important drops. For instance spiders only drop string and blazes don't drop anything. I'm unsure if it is just this mod or one of my other ones is conflicting in some weird way.

**Comment by Pyrofab** [comment]
Working as intended ! The "important drops" you are talking about only happen when mobs are killed by a player. Note that you get mob-specific drops instead, like music discs. To fix this behaviour, try finding a "Humanity" enchant book in a nether fortress.

**Comment by ravensniper72** [comment]
I would suggest noting this in the wiki info so it is known by users.
