### ISSUE TITLE
Little misspelling.

### ISSUE THREAD

**Issue by K0-RR** [Ladysnake/Requiem#197]
![Screen Capture_20201211121240](https://user-images.githubusercontent.com/43277609/101897596-17392700-3bab-11eb-85bb-8514b1535e3b.png)
![Screen Capture_20201211121203](https://user-images.githubusercontent.com/43277609/101897599-17d1bd80-3bab-11eb-98aa-2da6828c6c55.png)

**Comment by Pyrofab** [comment]
._.
