### ISSUE TITLE
[Even weirder mod conflict] Crash when these 7 mods are loaded alongside.

### ISSUE THREAD

**Issue by K0-RR** [Ladysnake/Requiem#200]
Fabric Loader 0.10.8. If just one of the mods with bold names isn't present then the game loads normally.

Mods:
fabric-api-0.28.0+1.16
modmenu-1.14.13+build.19
curios-fabric-0.0.10-1.16.3
**autoswitch**-2.11.6 OR **Autoswap** 1.16.2-fabric0.17.2-1.0.1 - doesn't matter
**bedrockify**-0.2.0-1.16.2+
**Croptopia**-1.0.5-1.16.X-FABRIC
**crumbs**-1.0.2+1.16.4-fabric
**cullleaves**-1.0.0
**requiem**-1.3.0
**rings-of-flight**-v1.1+1.16.4

crash report - https://hatebin.com/wlbbmciqrc
latest.log - https://hatebin.com/asfzvqrccv

**Comment by K0-RR** [comment]
So I don't know. Open issues on Their Githubs too?

**Comment by Pyrofab** [comment]
That's exactly the same crash as before, just a different set of mods changing the load order
