### ISSUE TITLE
Zombie resurrection fails with Jumploader

### ISSUE THREAD

**Issue by joeyjumper94** [Ladysnake/Requiem#201]
suffocating in sand blocks in a desert does not result in me becoming a husk
getting killed by a zombie doesn't turn me into a zombie,
drowning does not turn me into a drowned.
burning to death in lava in the nether does not convert me into a wither skeleton.

**Comment by Pyrofab** [comment]
Oh, that looks like a bug. I can confirm it doesn't seem to work in the latest release.

**Comment by Pyrofab** [comment]
Should be fixed now, thanks for the report !

**Comment by joeyjumper94** [comment]
conversion to husk? yes
conversion to zombie? no
conversion to wither skeleton? yes
conversion to drowned? yes

**Comment by Pyrofab** [comment]
So everything works except zombies ?

**Comment by joeyjumper94** [comment]
everything works except turning into a zombie from getting killed by zombies

**Comment by Pyrofab** [comment]
Do you use other mods ?

**Comment by joeyjumper94** [comment]
yeah

**Comment by joeyjumper94** [comment]
how do you detect if a player was killed by a zombie? is it by looking of some data tag?

**Comment by Pyrofab** [comment]
That resurrection is defined [here](https://github.com/Ladysnake/Requiem/blob/1.16/src/main/resources/data/requiem/requiem_resurrections/zombie.json), and it uses the [zombie entity tag](https://github.com/Ladysnake/Requiem/blob/1.16/src/main/resources/data/requiem/tags/entity_types/zombies.json)

**Comment by joeyjumper94** [comment]
gonna see what happens if i run just jumploader with fabric api and requiem

**Comment by joeyjumper94** [comment]
just by itself. i was disembodied by the zombie, no transformation

**Comment by Pyrofab** [comment]
I can't actually reproduce this bug, it seems to work fine for me 😕

**Comment by joeyjumper94** [comment]
are you using jumploader?
using a regular fabric installation does cause the expected result, but conversion to zombie fails if you use jumploader to load this in a forge installation. https://www.curseforge.com/minecraft/mc-mods/jumploader

**Comment by joeyjumper94** [comment]
[latest.log](https://github.com/Ladysnake/Requiem/files/5759894/latest.log)
this is the log if when i use jumploader to load this in a twitch launcher/forge installation

**Comment by Pyrofab** [comment]
Wait, this has probably nothing to do with Jumploader. You only turn into a zombie if a zombie could have naturally spawned where you died.
