### ISSUE TITLE
Graphical Glitches on vanilla-compatible servers with this mod on

### ISSUE THREAD

**Issue by jacekjarosz55** [Ladysnake/Requiem#202]
On Hypixel, with this mod enabled, scoreboard becomes invisible, colored glowing effect doesn't work, and the random names of npcs are visible, even though they shouldn't
![2020-12-29_15 03 10](https://user-images.githubusercontent.com/72438686/103290618-4abce380-49ea-11eb-9dd0-3456029ed8c3.png)

I'm on minecraft 1.16.4

**Comment by Pyrofab** [comment]
I would personally suggest not playing on a vanilla server with a modded client but I guess it counts as a bug. Are you sure these come from requiem and not another mod ? Do you have Pandemonium installed too ?

**Comment by jacekjarosz55** [comment]
> I would personally suggest not playing on a vanilla server with a modded client but I guess it counts as a bug. Are you sure these come from requiem and not another mod ? Do you have Pandemonium installed too ?

yeah, I've deleted all other mods to try it, and didn't have pandemonium installed. I understand this may be caused by server not having the mod, but it just seemed unexpected.

**Comment by Redfan2** [comment]
I tested it with Requiem 2.0.0-beta.16 on Hypixel and it works correctly
![2023-08-13_12 56 37](https://github.com/Ladysnake/Requiem/assets/114088095/24a88d86-507b-4819-8d16-94d45b899e9c)
