### ISSUE TITLE
resurrect as drowned?

### ISSUE THREAD

**Issue by joeyjumper94** [Ladysnake/Requiem#206]
instead of just being disembodied when a player drowns, what if drowning converted a player to a drowned?

**Comment by Pyrofab** [comment]
We initially thought of it but it wasn't added because it seemed too easy to jump in a pond and turn into a drowned. However I guess we can restrain it to ocean biomes, that would probably make sense.

**Comment by Pyrofab** [comment]
Feature added in 1.4.3 !
