### ISSUE TITLE
Mobs have broken hp when possesed

### ISSUE THREAD

**Issue by K0-RR** [Ladysnake/Requiem#209]
All mobs hp drop to 3 or 2 hearts when possessed.

**Comment by Pyrofab** [comment]
That sounds... normal ? Unless you have no Attrition effect.

**Comment by K0-RR** [comment]
I thought about this being a functionality when I saw that as an Iron Golem I have 10 hearts so like 20%? Where can I find more info about this Attrition effect?

**Comment by Pyrofab** [comment]
Attrition removes 20% of your health for every level, capping out at level IV. I guess we should write that down somewhere...

**Comment by K0-RR** [comment]
Also this:
![2021-01-02_12 09 36](https://user-images.githubusercontent.com/43277609/103456111-67f7f780-4cf3-11eb-873d-640fee252f97.png)

I don't know how to report this

**Comment by Pyrofab** [comment]
Huh, Trinkets interaction I assume ? What are the other mods adding stuff there ?

**Comment by K0-RR** [comment]
On the ss there are: Inventory Tabs, Trinkets, Curios API, Nourish (little carrot icon), Villager Names (the white text under the Crafting text)

And the "press world 2 to dissociate" doesn't mean anything to me. Which key I need to press?

**Comment by K0-RR** [comment]
Should I open an issue about compat with these mods?

**Comment by Pyrofab** [comment]
Yes a separate issue would be preferable. Thanks for all the reports by the way !

**Comment by Pyrofab** [comment]
(Moved the last issue to #212)
