### ISSUE TITLE
1.4.4 version not turning on

### ISSUE THREAD

**Issue by J3LL4** [Ladysnake/Requiem#214]
I've encountered a crash when trying to run a 1.4.4 version of the mod on fabric 1.16.4.
[Here's my crash log](https://github.com/Ladysnake/Requiem/files/5764183/crash-log.txt)

**Comment by Pyrofab** [comment]
Ah, you need to update Fabric API. I guess I should have bumped the required version...

**Comment by J3LL4** [comment]
Oh, whoops! Just realized I don't have it installed. Sorry!
