### ISSUE TITLE
Requiem-specific key bindings are reset when you exit and restart the game

### ISSUE THREAD

**Issue by James103** [Ladysnake/Requiem#222]
Currently, when you exit the game and restart the Minecraft process itself (not just when entering a new world), Requiem-specific keybinds get unconditionally reset. For example:
1. Set `[Requiem] Dissociation` keybind to `~` (or grave accent)
2. Exit the game
3. Restart the game
4. Open the controls menu.
5. Notice that `[Requiem] Dissociation` keybind has been reset to `\`.

Minecraft 1.16.4
Requiem 1.4.4
Pandemonium 1.4.4
Fabric API 0.29.3
Fabric loader 0.11.0

**Comment by Pyrofab** [comment]
Thanks for the report ! We are already aware of the issue and it will be fixed in the next update.
