### ISSUE TITLE
When you stop possessing a creature, its fall distance gets reset.

### ISSUE THREAD

**Issue by James103** [Ladysnake/Requiem#223]
Currently, when you stop possessing a creature right before it would take fatal fall damage, the creature survives and takes minimal damage, as if the fall distance was reset when you stop possessing a creature. I would expect for the fall distance to be preserved, meaning that the creature surviving was a side effect of unintended behavior.

To reproduce:
1. Possess any creature capable of taking fall damage.
2. Run `/tp @p ~ ~50 ~` (Note: If the creature despawns, that is bug #221 taking effect. Repeat step 1 if that happens)
3. Right before the creature lands, stop possessing the creature.
4. If you timed it right, you should see the creature survive rather than taking fatal fall damage.

Discovered while testing #221

**Comment by Pyrofab** [comment]
That makes sense, I should have probably seen that issue coming.
