### ISSUE TITLE
You can't shoot wither skulls manually when possessing a Wither

### ISSUE THREAD

**Issue by James103** [Ladysnake/Requiem#224]
Currently, when you possess a Wither, you can fully control its movement, but:
1. [ ] (a) You can't manually shoot Wither Skulls yet.
2. [ ] (b) Possessed Withers still shoot Wither Skulls of their own accord, ignoring the possessor.

As for shooting a Wither Skull, you should shoot a black Wither Skull if you aim near an entity when pressing the shoot key. If you are not aiming at an entity, you should instead shoot a blue Wither Skull.

To reproduce:
1. Download [this datapack](https://github.com/Ladysnake/Requiem/files/5826699/test_wither_skull.zip). It should show up as `file/test_wither_skull` in game.
2. Summon a Wither.
3. Possess the summoned Wither.
4. Try to shoot a Wither Skull. This currently fails.
5. Summon some non-undead creatures. Notice that the possessed Wither automatically shoots at the creatures without your consent.

Minecraft 1.16.4
Requiem 1.4.4
Pandemonium 1.4.4
Fabric API 0.29.3
Fabric loader 0.11.0

**Comment by Pyrofab** [comment]
I'll count this as a feature request, as it requires changing how the Wither works. Also possessing bosses is still currently unsupported.
