### ISSUE TITLE
Incorrect translation string: "pandemonium:tooltip.witch_brew_base"

### ISSUE THREAD

**Issue by James103** [Ladysnake/Requiem#227]
Currently, the tooltip that should say "Witch's Brew Base" instead says this:
![image](https://user-images.githubusercontent.com/37945304/105067538-65acd180-5a45-11eb-9f2a-1fba1554cfe6.png)

The translation key is invoked here:
https://github.com/Ladysnake/Requiem/blob/5fda90d6a4db32866d7f2e08593003e7fdbaf045/src/main/java/ladysnake/requiem/client/RequiemClientListener.java#L177
and defined here:
https://github.com/Ladysnake/Requiem/blob/5fda90d6a4db32866d7f2e08593003e7fdbaf045/expansions/pandemonium/src/main/resources/assets/pandemonium/lang/en_us.json#L2

Minecraft 1.16.4
Requiem 1.4.4
Pandemonium 1.4.4
Fabric API 0.29.3
Fabric loader 0.11.0

**Comment by Pyrofab** [comment]
Ah. Yes I'm bad.
