### ISSUE TITLE
Vanilla command "/team add <team> ["displayName"] not working when mod is active

### ISSUE THREAD

**Issue by pleasejustletmehaveafuckingusername** [Ladysnake/Requiem#231]
Not entirely sure if it is requiem, pandemonium, or both.

**Expectation:**Using the command "/team add team1 ["example"]" should work.

**Result:**When requiem and pandemonium are both installed, using the command will throw back the error message"An unexpected error occurred."

**Comment by Pyrofab** [comment]
Ah yes, pretty sure I know what the issue is. Thanks for the information, makes it easier to debug.

**Comment by Pyrofab** [comment]
Actually, this issue still occurs in the latest release.
