### ISSUE TITLE
Became desynced from hosted

### ISSUE THREAD

**Issue by dMoonShadowElf** [Ladysnake/Requiem#233]
so i was a zombie and i afked in water and the zombie converted to drown and the drown while following my spirit was not under my control but did stop me from possessing others or even the drown i let them burn in sunlight that seemed to fix it

**Comment by Pyrofab** [comment]
Do you have Immersive Portals by any chance ?

**Comment by Pyrofab** [comment]
Seeing as this does not happen under regular circumstances, I cannot do much without more details.
