### ISSUE TITLE
Minecraft crashes on death with Chest Cavity installed

### ISSUE THREAD

**Issue by alexbell962** [Ladysnake/Requiem#237]
Minecraft crashes with this mod with code: 0 while Lithium is installed.

**Comment by alexbell962** [comment]
Wasn't Lithium, but another mod interfering with death.

**Comment by Pyrofab** [comment]
Which mod then ?

**Comment by alexbell962** [comment]
Chest Cavities

**Comment by UpcraftLP** [comment]
I can't seem to reproduce this issue.

**Comment by stormdirus2** [comment]
Haven't ever been able to recreate this issue lol .-.

**Comment by Pyrofab** [comment]
Assuming fixed since it cannot be reproduced
