### ISSUE TITLE
"Blur (Fabric)" mod incompatibility

### ISSUE THREAD

**Issue by jdnoble3** [Ladysnake/Requiem#238]
Not necessarily incompatible, but as a Wandering Spirit (using Origins mod fyi) the background doesn't blur and rather turns entirely black.

Sure this is neat but I'm not sure it was intended.

![image](https://user-images.githubusercontent.com/63684195/108003412-bb32ba80-6fc0-11eb-88b3-29204f8a53f8.png)

**Comment by williambl** [comment]
Looks like [Satin#13](https://github.com/Ladysnake/Satin/issues/13)

**Comment by Pyrofab** [comment]
Yup, installing the [latest 1.16 version of satin](https://www.curseforge.com/minecraft/mc-mods/satin-api/files/3070595) should fix it
