### ISSUE TITLE
Multiplayer hardcore flat out does not work

### ISSUE THREAD

**Issue by Pyrofab** [Ladysnake/Requiem#240]
Dying in multiplayer as a remnant systematically puts you in spectator mode, rather than respawning you as a spirit.

**Comment by Tigereye504** [comment]
This mod is conceptually incompatible with hardcore mode, the whole point is to not properly die when you are killed. What are you wanting the mod to do that wouldn't completely invalidate hardcore mode?

**Comment by Pyrofab** [comment]
In singleplayer hardcore, you respawn as a spirit a single time. You cannot regenerate a human body, and the game is over if you die while possessing a mob.
