### ISSUE TITLE
Suggestion: "Failsafe" Option

### ISSUE THREAD

**Issue by IdrisQe** [Ladysnake/Requiem#246]
Currently there's a slight issue when you die in certain places which makes it... Well, impossible to proceed.

If you (somehow) die inside a multi-block-thick wall, you can't get out.

If you die in The End, especially before you kill the Dragon, you can't get out especially since no Undead spawn in the End
This may be bypassable by falling into the void? Not sure since I'm using a mod currently that teleports you back to land if you fall in, and regen in dead-form is too fast to make up the difference.

And likewise, in some modded dimensions such as The Bumblezone there's no way to get out if you die since you normally need to break blocks to get out, and there's no Undead to possess...

So it'd be neat to have a "failsafe" option available to all players even with cheats off...
I'm thinking either by keybind or command. Either it kills you in dead-form, causing the vanilla death screen and respawn mechanics, or it teleports you back to the Overworld since that's (almost) guarenteed to have Undead in it and is where the most gameplay happens.

**Comment by stormdirus2** [comment]
You can phase through blocks
You can do this through multiple block layers, just push against it until you reach somewhere.
You can get out of the end, spirits can take void damage, use this to exit the end

**Comment by IdrisQe** [comment]
Wait you can actually phase through multiple blocks? I thought it was just single-layers.
Though it would still be nice to have since, as stated, some mods make falling into the void not fatal, and that makes it otherwise impossible to exit the End.

**Comment by stormdirus2** [comment]
> Wait you can actually phase through multiple blocks? I thought it was just single-layers.

Yes you can, it's been possible for a decent amount of time now.

> Though it would still be nice to have since, as stated, some mods make falling into the void not fatal, and that makes it otherwise impossible to exit the End.

I guess. However, if you don't want the end to be softlocking the player but still want the void not to kill, you should get [Unforgiving Void ](https://www.curseforge.com/minecraft/mc-mods/unforgiving-void)(This is different from forgiving void). It makes it so falling through the void teleports you to the nether. (With fire resistance)
This mod works perfectly with Requiem, and should be a decent fix to the problem you are experiencing.

**Comment by IdrisQe** [comment]
Oh hey, I didn't realize Unforgiving Void was a thing for Fabric! I'll add that! Though it's still not my favourite way of dealing with the void, it'll do much better.

**Comment by GuiTaek** [comment]
By the way, this should be fixed now as now, you can get to the overworld through possessing endermans

**Comment by Pyrofab** [comment]
Good point
