### ISSUE TITLE
As a Pillager, Vindicator, or Evoker, you are unable to ride Ravagers yet.

### ISSUE THREAD

**Issue by James103** [Ladysnake/Requiem#249]
Currently, if you are currently possessing a Pillager, Vindicator, or Evoker, you are unable to ride Ravagers, even though it is possible to get naturally spawning Pillagers, Vindicators, or Evokers riding Ravagers through raids in hard difficulty. 

For consistency, I suggest that when you are possessing a Pillager, Vindicator, or Evoker, you can click on a Ravager to ride it. Once you are on the Ravager, you should then be able to control the Ravager you're riding.

**Comment by Pyrofab** [comment]
Approved !
