### ISSUE TITLE
As a Chicken, you are constantly pushed forward if you are ridden by a baby zombie.

### ISSUE THREAD

**Issue by James103** [Ladysnake/Requiem#251]
As of Requiem 1.5.0, Pandemonium 1.5.0, and Minecraft 1.16.4, when you possess a Chicken ridden by a baby Zombie, you are constantly pushed forward in the direction you're facing, meaning that you can never stay still in such a configuration. To reproduce:
1. Summon (or find) a Chicken ridden by a baby Zombie.
`/summon minecraft:chicken ~ ~ ~ {Passengers:[{id:"minecraft:zombie",IsBaby:1b}]}`
2. Possess the Chicken that is being ridden.
3. Notice that you can't stand still, you are constantly being pushed forward by the baby zombie.

**Comment by Pyrofab** [comment]
That one sounds kinda normal ? The zombie is forcing you to move.

**Comment by supersaiyansubtlety** [comment]
This behavior sounds good to me.
