### ISSUE TITLE
Possessed Zombies riding Chickens are unable to control said Chickens.

### ISSUE THREAD

**Issue by James103** [Ladysnake/Requiem#252]
As of Requiem 1.5.0, Pandemonium 1.5.0, and Minecraft 1.16.4, when you possess a baby Zombie that is riding a Chicken, you are unable to control the chicken, even though the chicken gains a speed boost from being ridden by the zombie when neither is being possessed.

(This also applies to Zombified Piglins riding Striders)

**Comment by Pyrofab** [comment]
Fixed in 2.0.0-alpha.10 ☑
