### ISSUE TITLE
Climbing stops working in both Bewitchment and Origins

### ISSUE THREAD

**Issue by MoriyaShiine** [Ladysnake/Requiem#257]
I couldn't find the reason for this, but my first guess would be either Requiem overwrites LivingEntity#isClimbing or sets Entity#horizontalCollision to false every tick

**Comment by Pyrofab** [comment]
Yes, almost definitely the issue that was fixed in [this commit](https://github.com/Ladysnake/Requiem/commit/550d46b16ee8139ffda5c6fae5de31a56c80e7db) that I need to release

**Comment by MoriyaShiine** [comment]
Fixed in 1.5.1
