### ISSUE TITLE
Minecraft Gets Stuck Loading New World In Single Player.

### ISSUE THREAD

**Issue by toErIpNid** [Ladysnake/Requiem#258]
I'm testing out a modpack, and everything was good until I added Requiem and Memento Mori. Then when attempting to create a new world, it get stuck loading after I selected my soul type, origin, and class.

Modlist: https://imgur.com/a/oqJ1tUh

Using latest Fabric version 0.11.3.

**Comment by Pyrofab** [comment]
Could I see your latest log ?

**Comment by toErIpNid** [comment]
After some more fiddling, it seems like choosing demon>wandering spirit is the cause or part of what causes the world not to load. As I accidentally picked mortal before and spawned in normally. 
[latest.log](https://github.com/Ladysnake/Requiem/files/6181714/latest.log)

**Comment by SekoiaTree** [comment]
Did some more testing: I think this is an origins bug due to multiple origins layers existing. I think I found a way around it though: just press escape on the dirt screen, and it loads up for me.

**Comment by Pyrofab** [comment]
I assume we can't really do much about this, so I'll close this issue.
