### ISSUE TITLE
how do you use the commands

### ISSUE THREAD

**Issue by fallenpro** [Ladysnake/Requiem#260]
i want to try and use the "/requiem possession" command but dont know how as im kinda confused about how you force yourself to possess a mob forcefully

**Comment by fallenpro** [comment]
i think i should clarify, mainly how you know what to type in for the entity you need to control, so if there's some sort of list someone can send me i'd like that

**Comment by Pyrofab** [comment]
That's a traditional entity selector (`@e`), you can find information about it on the minecraft wiki: https://minecraft.fandom.com/wiki/Commands#Target_selectors
