### ISSUE TITLE
How can I possess players?

### ISSUE THREAD

**Issue by aeswda** [Ladysnake/Requiem#261]

**Comment by Pyrofab** [comment]
Short answer: you cannot possess live players.
Long answer: if you use the Pandemonium experimental addon, remnant players can dissociate from their body, leaving an empty shell behind. You can possess other players' shells to start impersonating them.

**Comment by aeswda** [comment]
if i'm a emnant players,how can i have body

**Comment by aeswda** [comment]
> Short answer: you cannot possess live players.
> Long answer: if you use the Pandemonium experimental addon, remnant players can dissociate from their body, leaving an empty shell behind. You can possess other players' shells to start impersonating them.

if i'm a emnant players,how can i have body

**Comment by Pyrofab** [comment]
If you are a wandering spirit, you cannot. If you are a regular demon, and you have pandemonium installed, you can use the `dissociate` keybind while you are a regular player (not dead).

**Comment by EduardoNathiel** [comment]
I tried to look for this "the Pandemonium" to add player shells, but I couldn't find it anywhere. Would you have a link? Or another mod to recommend, thanks in advance.

**Comment by Pyrofab** [comment]
The Pandemonium plug-in is currently available as an additional file on [Curseforge](https://www.curseforge.com/minecraft/mc-mods/requiem/files) and [modrinth](https://modrinth.com/mod/requiem/versions).

**Comment by EduardoNathiel** [comment]
Hmm ... Whenever I search, I never find anything, strange.

**Comment by EduardoNathiel** [comment]
Oh thx, i find
