### ISSUE TITLE
Possesing a summoned player shell crashes the game

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Requiem#263]
Whenever I summon the player_shell entity and possess it, my game crashes, I know this feature probably doesn't need fixing as there is no need to possess an empty Steve or Alex skin summoned with commands, but I was playing around with it and thought I'd flag it to let you know.

I am using MC1.16.5, Requiem, Pandemonium and Fabric API

**Comment by Pyrofab** [comment]
Known issue, not super high priority but yes it will be fixed.
