### ISSUE TITLE
Dissociating whilst gliding with an elytra crashes the server.

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Requiem#266]
If a player is flying with an elytra, and successfully dissociates, the server will crash, with the following error:

`
[crash-2021-04-02_20.40.55-server.txt](https://github.com/Ladysnake/Requiem/files/6248909/crash-2021-04-02_20.40.55-server.txt)
`

**Comment by Pyrofab** [comment]
Oh, that should be fixed with the next update.

**Comment by Pyrofab** [comment]
Confirmed fixed in 1.6.0 and up.
