### ISSUE TITLE
Possessed Entities Take (Too Much) Fall Damage

### ISSUE THREAD

**Issue by kestrel1110** [Ladysnake/Requiem#271]
I have been playing on a modded server with requiem and a few origins mods, and I am a wandering spirit. However, when I possessed a drowned and put on netherite feather falling 4 boots and full protection 4 netherite armor, I died after falling a very small distance. Then I did some testing and found that mobs will only experience this bug when possessed, and they survive the fall that killed my first drowned when I'm not in them. And yes, that drowned was at full health.
Also, as another test,I don't I spawned feather falling level 2000 boots, and the mobs will still die. I don't think this is an intentional feature, and I hope it gets fixed soon :/

**Comment by Pyrofab** [comment]
Thanks for the report ! This should be fixed in versions 1.6.0 and up.
