### ISSUE TITLE
Infinite loading bug when choosing Wandering Spirit origin

### ISSUE THREAD

**Issue by JoJazzy** [Ladysnake/Requiem#274]
I'm including Requiem in my modpack allong with Origins, Fantasycraft, Extra Origins, Mob Origins, Origins: Classes and Mermod.
When choosing the Demon soul type and then the Wandering Spirit origin it makes the game load indefinitely when loading for the first time. If I close the game and re-open the world it loads with no issues.
Here's the log of the game loading for the first time (I found the error at the 2nd last line in the log):
[latest.log](https://github.com/Ladysnake/Requiem/files/6331915/latest.log)

**Comment by seaglade** [comment]
It's a bug with Origins. If you press the ESC key it fixes it.

**Comment by JoJazzy** [comment]
> It's a bug with Origins. If you press the ESC key it fixes it.

I would still like it be removed if possible

**Comment by SekoiaTree** [comment]
We're unsure on which side the bug is on. I've experienced sometimes a similar bug with Haema, but the bug is *really* hard to figure out, especially since we're not sure on which side the bug is on. If it's on the Origin's side, we can't do anything about it, Origins has to fix it. I *think* the bug is caused by having 2 layers of origins.

**Comment by SekoiaTree** [comment]
Also to note; we've already reported this to Origins, but we haven't gotten a response yet. Also, you seem to have issues with fantasycraft :P

**Comment by JoJazzy** [comment]
> Also to note; we've already reported this to Origins, but we haven't gotten a response yet. Also, you seem to have issues with fantasycraft :P

Yea I know about that but it seems to be mostly recipes and it didn't change much, thanks a lot though, I really appreciate it

**Comment by ryleu** [comment]
I think this duplicates #258

**Comment by Pyrofab** [comment]
Yup, it's a duplicate *and* we can't really do much about it either as far as I know.
