### ISSUE TITLE
License displayed on Modrinth page is incorrect

### ISSUE THREAD

**Issue by triphora** [Ladysnake/Requiem#276]
[Your license](https://github.com/Ladysnake/Requiem/blob/1.16/LICENSE-CODE) says the code of this project is GPL-2.0 w/ MC exception. [Your Modrinth page](https://modrinth.com/mod/bYmqMxlQ) displays `ARR` as the license. While this is correct for the art, the majority of the project is the code, not the art; it would probably be better if the project on Modrinth displayed `CUSTOM` as the license rather than `ARR`.

**Comment by Pyrofab** [comment]
Thanks for the report, it's been updated.
