### ISSUE TITLE
[Better Graves] Graves spawn upon disassociation with any mobs

### ISSUE THREAD

**Issue by Awoo-desu** [Ladysnake/Requiem#280]
This includes any monsters disassociated when playing with the demon Origin (Allowing you to disassociate anytime). Also includes Golems which have no inventory. The graves left behind are empty, so they shouldn't be spawning if nothing is in-inventory.

**Comment by Pyrofab** [comment]
Graves shouldn't spawn anymore in the latest version, thanks for the report!
