### ISSUE TITLE
Duplicating Body

### ISSUE THREAD

**Issue by deadspidervenom** [Ladysnake/Requiem#283]
Not sure how this happened or how to replicate it, but i was looking for animals (possessing them and walking home) and when i went back to my bod i saw it had moved, and when i possess it... well
![image](https://user-images.githubusercontent.com/12871122/116929466-51b36700-ac13-11eb-8f49-368d2561f83d.png)

**Comment by Pyrofab** [comment]
Huh. If you can find steps to replicate this, it would be quite helpful.

**Comment by deadspidervenom** [comment]
Can confirm how to replicate.

Simply leave you body and fly till the chunks unload, when you return, all shells will duplicate, i now have 4 bodies.

This would be a really cool feature if it was controllable, making spare shells to possess if you die instead of needing to possess a zombie or something. 

Maybe make it so if you capture and cure a plain zombie it becomes a "unclaimed shell" then the first person to possess it claims it.

![image](https://user-images.githubusercontent.com/12871122/116933924-1451d800-ac19-11eb-8143-70c23afcf400.png)

**Comment by deadspidervenom** [comment]
This also dupes you inventory, also dupes if you go through a portal(makes it easier if you have immersive portals), now at a spare body count of 11 thanks to portals. 3 of them are else where

![image](https://user-images.githubusercontent.com/12871122/116939478-3f402a00-ac21-11eb-9204-07e348b05805.png)

**Comment by James103** [comment]
I bet something went wrong when unloading and/or loading the player shells causing them to duplicate. Can you please try reproducing this again? If you can reproduce the issue, can you please attach the full game log?

**Comment by deadspidervenom** [comment]
![image](https://user-images.githubusercontent.com/12871122/116955964-e4222d80-ac48-11eb-8107-281ee0cb1506.png)
Replicated for the fourth time might i add @James103  It was not a one time thing.

Here is the games logs 
https://paste.srnyx.xyz/isuhoyilol.yaml

I had some troubles replicating it cause i was not going far enough, or stupidly left my body in loaded spawn chunks. Did not help that i had to kill myself cause i got stuck as a nether mob cause i had no shell in the nether so i could not leave it (also a bug i was gonna report, can't leave monsters you enter if you dont have a shell in that dimension (in pandemonium)
