### ISSUE TITLE
Can you possess a wither?

### ISSUE THREAD

**Issue by XenoProgram** [Ladysnake/Requiem#284]
Im just wondering, can you possess a wither? I always see the camera effect every time i click on a wither but dont possess it. Me and my friend have been trying for a while. if you have the answer please tell me!

**Comment by Pyrofab** [comment]
Nop, you cannot by default, you getting the effect is a bug. However, you can use a datapack to remove the wither from the blacklist yourself (https://ladysnake.github.io/wiki/requiem/configuration).

**Comment by XenoProgram** [comment]
im not smart enough to do that
