### ISSUE TITLE
While possessing a Phantom, its rotation in the vertical direction is inverted.

### ISSUE THREAD

**Issue by James103** [Ladysnake/Requiem#286]
As of Minecraft 1.16.4, Requiem 1.6.2, and Pandemonium 1.6.2, when you possess a Phantom, the vertical rotation of its body is the opposite of what you would normally expect. For example, when you are looking down, it appears as if the Phantom you are possessing is looking upwards, and vice versa.
![image](https://user-images.githubusercontent.com/37945304/116954381-7c261400-ac55-11eb-8c4b-a4870dd18295.png)
![image](https://user-images.githubusercontent.com/37945304/116954393-8516e580-ac55-11eb-915f-61e71dfab7c7.png)

**Comment by Pyrofab** [comment]
Yeah, I did notice this bug before, but it's quite minor so I doubt I will fix it super soon.

**Comment by Pyrofab** [comment]
Fixed in 2.0.0-alpha.9 ☑
