### ISSUE TITLE
Client crash when possessing a mob - crimson-moon incompatibility

### ISSUE THREAD

**Issue by schindlershadow** [Ladysnake/Requiem#290]
Description: Rendering entity in world

Crash report:
https://pastebin.com/GkLcRL8N

Minecraft Version: 1.16.5
requiem: Requiem 1.6.2
requiemapi: Requiem-API 1.6.2

Possible mod incompatibility

**Comment by schindlershadow** [comment]
Confirmed it does not crash when removing crimson-moon-2.0.4-1.16.5

**Comment by Pyrofab** [comment]
Yup, this is caused by Crimson Moon bundling a snapshot version of Satin API. You can fix it by manually installing [a compatible version of the latter](https://www.curseforge.com/minecraft/mc-mods/satin-api/files/3070595).
