### ISSUE TITLE
Dissociation Keybind not working / appearing.

### ISSUE THREAD

**Issue by ripnonfegames** [Ladysnake/Requiem#291]
Hello, I dont know what the Dissociation keybind is and I cant change it in the control menu, Can someone tell me how to fix this?

**Comment by Pyrofab** [comment]
You mean, you can't find it ? It should be called "[Requiem] Dissociation".

**Comment by K0-RR** [comment]
Hi, it is not working - I have it set like this
![image](https://user-images.githubusercontent.com/43277609/117508906-9a5b7f00-af89-11eb-90a5-083fdd5eea17.png)
and it does nothing.

**Comment by stormdirus2** [comment]
> Hi, it is not working - I have it set like this
> ![image](https://user-images.githubusercontent.com/43277609/117508906-9a5b7f00-af89-11eb-90a5-083fdd5eea17.png)
> and it does nothing.

@RDKRACZ

Are you in a mob that allows dissociation or do you have pandemonium and no attrition?

**Comment by K0-RR** [comment]
>Are you in a mob that allows dissociation

Do Villagers and Zombies allow? If yes then it does not work for me.

>do you have pandemonium and no attrition

Yes

**Comment by Pyrofab** [comment]
Try rebinding it to something else ? It gets a bit finnicky sometimes.

**Comment by TreBoi** [comment]
Same bug for me
