### ISSUE TITLE
whenever i possess a body and press E my game crashes

### ISSUE THREAD

**Issue by pithoH** [Ladysnake/Requiem#298]

**Comment by pithoH** [comment]
![Capture2](https://user-images.githubusercontent.com/83868572/117538883-78f1a600-b010-11eb-9b6c-a91d7eefcdc0.JPG)

**Comment by K0-RR** [comment]
Works for me, I think you should share your mod list and post the full log.

**Comment by Pyrofab** [comment]
Try manually installing the latest version of satin for 1.16 from https://curseforge.com/minecraft/mc-mods/satin-api
