### ISSUE TITLE
Shell duplication

### ISSUE THREAD

**Issue by SerrgeiKr** [Ladysnake/Requiem#300]
When I go to Nether, possess a zombie pigman and then die my shells get duplicated

.
![2021-05-09_21 23 17](https://user-images.githubusercontent.com/47196993/117583074-d3246100-b10d-11eb-870d-358c62f98736.png)
![2021-05-09_21 24 10](https://user-images.githubusercontent.com/47196993/117583076-d4558e00-b10d-11eb-9cae-3db953e9d304.png)
![2021-05-09_21 24 54](https://user-images.githubusercontent.com/47196993/117583077-d4ee2480-b10d-11eb-9eb6-15b5eddfd134.png)
![2021-05-09_21 26 05](https://user-images.githubusercontent.com/47196993/117583078-d586bb00-b10d-11eb-8102-2367aab496b3.png)

**Comment by Pyrofab** [comment]
Shoot, I guess #283 was not fixed after all.

**Comment by Pyrofab** [comment]
Say, can you reproduce this bug with only requiem and pandemonium (and fabric api) installed ?

**Comment by James103** [comment]
> Say, can you reproduce this bug with only requiem and pandemonium (and fabric api) installed ?

And if so, can you please provide the corresponding game logs?

**Comment by SerrgeiKr** [comment]
Sorry, that was just me being dumb, I had Impersonate mod installed and that caused the glitch, so there's no bug actually.

**Comment by Pyrofab** [comment]
Could you elaborate on what glitch happened exactly ?

**Comment by SerrgeiKr** [comment]
I checked it again, Impersonate is not the reason, it works like #283, unloading, loading chunks makes that to happen.
[latest.log](https://github.com/Ladysnake/Requiem/files/6448587/latest.log)

**Comment by Pyrofab** [comment]
Chunk saving error eh ? Guess I may not have been as smart as I hoped on that one.

**Comment by Pyrofab** [comment]
Does it get fixed if you install [this mod](https://github.com/Ladysnake/Automatone/releases/download/0.3.4/automatone-0.3.4-optimized.jar) ?

**Comment by SerrgeiKr** [comment]
YES

**Comment by Pyrofab** [comment]
Brilliant, thanks !
