### ISSUE TITLE
Crash when running on server - Failed to set up Fabric environment

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Requiem#304]
Hi,
Unfortunately with the most recent version of Requiem, the server crashes during start up. I have also updated the Fabric API to the most recent version and I am still having issues.
Attached is the mclo.gs
https://mclo.gs/zyV8fca
![image](https://user-images.githubusercontent.com/59938827/117670023-6c4f8800-b19f-11eb-8a39-894873a639df.png)
Thank you for your time!

**Comment by Pyrofab** [comment]
It's a known issue, the fix will be out soon =)

**Comment by ghost** [comment]
> It's a known issue, the fix will be out soon =)

Ah, great! Thank you very much! Please keep up the hard work, the mod is amazing :D

**Comment by Pyrofab** [comment]
And there you go, fixed !
