### ISSUE TITLE
You can put armor on a mob that can't wear it by shift clicking.

### ISSUE THREAD

**Issue by SerrgeiKr** [Ladysnake/Requiem#306]

**Comment by Pyrofab** [comment]
I can't reproduce this issue, does it happen with a specific mod ?

**Comment by SerrgeiKr** [comment]
No, it's only Requiem and Pandemonium. Just open your inventory and shift click on an armor.

**Comment by Pyrofab** [comment]
Ah, shift clicking in the inventory. I may have indeed overlooked that.
