### ISSUE TITLE
Swimming as non-Drowned undead is possible and easy

### ISSUE THREAD

**Issue by Dual-Iron** [Ladysnake/Requiem#313]
You can swim as an undead just fine by sprinting underwater.

https://cdn.discordapp.com/attachments/592116208715956324/842163813355749426/Minecraft__1.16.5_-_Multiplayer_3rd-party_Server_2021-05-12_18-17-36.mp4

**Comment by Pyrofab** [comment]
Thanks for the report ! Shouldn't be so easy now.
