### ISSUE TITLE
Mobs can still use hotbar when they are not in the item_user.json

### ISSUE THREAD

**Issue by EntityIsMissing** [Ladysnake/Requiem#315]
Example zoglin can equip a diamond sword into its second slot in the inventory.
![zoglin](https://user-images.githubusercontent.com/84119705/118087811-9a38f600-b372-11eb-966e-530f5dd54040.JPG)

**Comment by Pyrofab** [comment]
Right, I did not consider the case where you only want an inventory for storage.

**Comment by EntityIsMissing** [comment]
Thanks for the fix! I was making carriers/attackers with a data pack and one of my testers showed me that carriers could still use the hot bar for attacks.

**Comment by EntityIsMissing** [comment]
> Right, I did not consider the case where you only want an inventory for storage.

Thanks for the fix! I was making carriers/attackers with a data pack and one of my testers showed me that carriers could still use the hot bar for attacks.
