### ISSUE TITLE
Consuming a stack of meat or bones that only has one item does not start the eating cooldown

### ISSUE THREAD

**Issue by Dual-Iron** [Ladysnake/Requiem#317]
# What works as intended
When you eat from a stack whose count > 1, you get a cooldown to healing further. 
# What doesn't
When you eat from a stack whose count = 1, you do **not** get a cooldown.
## Issue
This makes healing as an undead faster and easier than healing as a living being... which is odd. See video.

https://user-images.githubusercontent.com/31146412/118314558-4d643500-b4c2-11eb-8aea-ab76e17da683.mp4

**Comment by Pyrofab** [comment]
Nice catch !
