### ISSUE TITLE
Pigman Brutes/Piglin Brutes can equip armor, despite not showing such in the inventory

### ISSUE THREAD

**Issue by Dual-Iron** [Ladysnake/Requiem#325]
Using a dispenser, these mobs equip armor just fine, but can't unequip it unless replacing it with better armor.

https://user-images.githubusercontent.com/31146412/118376825-5d4e4880-b598-11eb-8771-7b941828fb6c.mp4

Alternatively, mods that introduce trinkets or vanity slots let you bypass the dispenser entirely. You still can't unequip it unless replacing it with better armor.

https://user-images.githubusercontent.com/31146412/118376730-d13c2100-b597-11eb-94ee-f41b05c7e144.mp4

This can be resolved in one of a few ways:
1. Allow donning and doffing armor through the inventory.
2. Allow donning through the inventory, but only allow swapping with better armor and not doffing.
3. Disallow donning armor for these mobs entirely.

I prefer 1, as piglins follow that behavior, and disallowing doffing takes a lot of control away from the player. Number 3 is my least favorite, as it directly contradicts vanilla. Nonetheless, any one of these resolves the inconsistency.

This also applies to any mobs that don't show armor, like pandas in Pandemonium.

**Comment by Pyrofab** [comment]
This is kind of intended ? Those mobs can't equip armor by themselves in vanilla, so you can't equip armor when playing as them.

**Comment by Dual-Iron** [comment]
Neither can most piglins or zombies. Additionally, piglins and zombies can't unequip armor, but Requiem stills allows it. The behavior for piglin brute armor management is simply inconsistent.

**Comment by Pyrofab** [comment]
Well to be perfectly frank, an armored piglin brute would be absurdly powerful and we'd like to discourage it. But Vanilla minecraft allows using dispensers on them, so that's the compromise we went with.

**Comment by Dual-Iron** [comment]
I'm confused—it's still possible to possess an armored piglin brute, but it's janky because you can't directly equip the armor. If you want to prevent brutes/pandas/foxes from donning armor, that's understandable, but the current behavior doesn't prevent that. It prevents _doffing_ armor.

This issue is about the fact that you can't put armor onto these mobs through the inventory, but can through a dispenser, which is inconsistent with other mobs of similar nature. *If this is not intended*, it is a bug. *If this is intended*, I suggest changing it, because it's very confusing behavior that's prone to hacky workarounds.

**Comment by Pyrofab** [comment]
You make a good point in that this is not really a sustainable solution. Armored piglin brutes are in our opinion fairly broken balance-wise, but the vanilla game allows them through dispensers. So even if we disallow equipping while they are being possessed, players will be able to equip them beforehand. I see 2 real solutions here:

- make piglin brutes really hard or even impossible to possess
- prevent dispensing armor onto piglin brutes entirely, even when not possessed

The latter solution is probably the easiest, even though it breaks vanilla behaviour, so I guess we'll go with that.

**Comment by Dual-Iron** [comment]
To be fair, with normal Requiem, piglin brutes _are_ pretty difficult and lengthy to safely possess, with needing to get them through a portal, keep them in there, then cure them—all the while piglins are likely mad at you and you're dealing with a mob that can likely 3 shot you.

With Pandemonium, however, that difficulty is negated. And I don't even have a comment for pandas with armor.

All in all, the latter makes the most sense for preventing piglin brutes having armor. It was fun having a piglin brute with a netherite helm, leggings, and boots with a Hiking Pack chestplate, but it was also ridiculously broken.
