### ISSUE TITLE
Screen does not tilt and hearts do not blink when taking damage as a mob

### ISSUE THREAD

**Issue by Dual-Iron** [Ladysnake/Requiem#328]
Simple enough.

https://user-images.githubusercontent.com/31146412/118381770-6b15c500-b5bc-11eb-8d76-8879c6e79d3c.mp4

**Comment by ryleu** [comment]
I noticed something was wrong, but I wasn't sure what it was.

**Comment by alexmozaidze** [comment]
I thought it was intentional. Like, when you take damage as a mob, you don't really take damage, but mob does. It'd be cool if there was an option to toggle screen shaking when in mob's body.

**Comment by Pyrofab** [comment]
That's an excellent excuse to mark this as a feature. We'll think about it I guess.

**Comment by Dual-Iron** [comment]
> I thought it was intentional. Like, when you take damage as a mob, you don't really take damage, but mob does. It'd be cool if there was an option to toggle screen shaking when in mob's body.

But you are the mob, i.e. your soul is in the mob's body. Like when your soul is in your player's body. Why would it be any different?

Also it makes it legitimately harder to identify when you take damage.
