### ISSUE TITLE
Crash when shift clicking fuel out of a furnace

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Requiem#331]
I have determined that Requiem 1.7.6 crashes whenever I shift click fuel out of a furnace. I have disabled all mods except for Requiem and Fabric API (0.34.2+1.16) and tried both with and without Cloth Config (4.11.26). This does not occur with Requiem disabled, so I'm fairly certain that it is the cause. It happens both in singleplayer and multiplayer.

It seems to be a simple IndexOutOfBounds exception, though I won't act like those haven't kept me up into the late hours of the night before. I wish you the best of luck on this. If you need any more details that you think I can provide, please do let me know.

[crash-2021-05-18_01.00.42-client.txt](https://github.com/Ladysnake/Requiem/files/6499453/crash-2021-05-18_01.00.42-client.txt)

**Comment by ghost** [comment]
After further testing, I found that Requiem 1.7.5 does not seem to have this issue, which would lead me to believe that this issue was introduced in 1.7.6 (maybe in [this](https://github.com/Ladysnake/Requiem/commit/7a755985905215455cbc9166785a09ae7fbed03c) commit since it relates to shift clicking). I hope this extra information helps to narrow down the issue.

**Comment by Pyrofab** [comment]
Found the issue, thanks for the detailed report !

**Comment by SekoiaTree** [comment]
<3 for jamalmarri, this is the best kind of report

**Comment by ryleu** [comment]
I was about to report the same thing then I saw this. +1!
