### ISSUE TITLE
Lag Induced Player Shell Duplication

### ISSUE THREAD

**Issue by zacharylott94** [Ladysnake/Requiem#342]
Given enough lag, player shells can be duplicated with rapid use of the dissociate keybind when using the Pandemonium addon.

How to Reproduce:
1. Induce lag. In my reproduction attempts, going through nether portals produced the best results. However, I discovered the bug during regular gameplay.
2. Rapidly dissociate by either rapidly tapping the keybind or holding the keybind down.

You should see many resulting shells, each with the same inventory.
![2021-05-28_10 10 27](https://user-images.githubusercontent.com/37595873/120006889-f751c000-bf9e-11eb-955b-b094f169f21e.png)
![2021-05-28_10 20 54](https://user-images.githubusercontent.com/37595873/120006909-fcaf0a80-bf9e-11eb-95f2-0a29e54ee987.png)

Mods used in testing:
The checked mods are the only ones enabled
![image](https://user-images.githubusercontent.com/37595873/120006824-e43ef000-bf9e-11eb-937a-25585aa9063b.png)

**Comment by Pyrofab** [comment]
Welp, thanks for the report !

**Comment by Pyrofab** [comment]
Ehm, the issue is fixed but curseforge is down so I can't upload the new version. Apologies for the inconvenience.
