### ISSUE TITLE
Features not working as a whole

### ISSUE THREAD

**Issue by FumpleWumper** [Ladysnake/Requiem#345]
Using the latest version of Requiem and Satin, I can't cure myself back into a human as the process only gives me Strength and keeps me as an undead mob, and Attrition doesn't go away

I am playing with Origins if it helps

**Comment by Pyrofab** [comment]
What happens if you wait for the strength effect to run out naturally ?

**Comment by FumpleWumper** [comment]
...Ah. THAT'S how it's supposed to work

Okay, so Attrition doesn't really go away, the time that it says is remaining just sort of stays frozen, is that also supposed to happen?

**Comment by Pyrofab** [comment]
Only supposed to happen if you are not human. Once you are cured, it should start ticking down.

**Comment by FumpleWumper** [comment]
Oh I see this was a huge misunderstanding then, thank you for your patience anyway!! ^^'
