### ISSUE TITLE
crash while loading world

### ISSUE THREAD

**Issue by LordDecay26** [Ladysnake/Requiem#346]
not necessarily you guy's fault, but there are errors in the latest.log that may have contributed to the crash, so im covering my bases. let me know if you can figure out what mod, if not yours, is causing the crash. im aware it could also be the Bladeborn origin mod that i have installed, but seeing as a crashlog wasnt generated, im not sure. 

im running Requiem 1.7.7

anyway here's the latest.log, it's literally too big to be pasted into pastebin. fuckin' strange.
https://www.mediafire.com/file/agdp3ibu7twxeey/latest.log/file

**Comment by Pyrofab** [comment]
That log doesn't seem to have much useful info :/

**Comment by LordDecay26** [comment]
yeah i know i couldnt make heads or tails of it :(

**Comment by Pyrofab** [comment]
Sorry I can't really know what went wrong so I'll just close this issue. If you have more info, feel free to reopen.
