### ISSUE TITLE
Ingame Crash while Trying to Find a Body

### ISSUE THREAD

**Issue by Blunder-G** [Ladysnake/Requiem#349]
I just become a demon and clicked a zombie... And my game... It's DEAD NOW ;(

Nevermind, here is the crash report: 
[crash-2021-06-07_11.35.01-client.txt](https://github.com/Ladysnake/Requiem/files/6607285/crash-2021-06-07_11.35.01-client.txt)

**Comment by Pyrofab** [comment]
Wouldn't you look at that ! You can use the 1.7.10 version, uploaded 1 hour ago 😄
