### ISSUE TITLE
Mob aggro is broken with Gobber2

### ISSUE THREAD

**Issue by KamiSami** [Ladysnake/Requiem#350]
Hi, i was wondering is there config for requiem and pandemonium somewhere other then in normal config that doesn't have pretty much anything in it? It had something but nothing i was thinking about of trying to change. Basically, there is issue i am having, when i possess mob, all other mobs attack me, this didn't happen before... I am hoping to find the cause of this so i wont be attacked as a mob again. This is happening with latest Requiem and pandemonium versions. Which are requiem-1.7.10 and requiem-pandemonium-1.7.10. I have some other mods aswell included, i can make list of them now and paste them below this message...

https://pastebin.com/dRm000MC

**Comment by Pyrofab** [comment]
For the configuration : https://ladysnake.github.io/wiki/requiem/configuration
For mobs attacking you, does this happen without any other mod ?

**Comment by KamiSami** [comment]
Not sure, i can test this out though. Just a moment and i'll test it out right now, gotta make new profile first so i can test if this happens without any other mods.

**Comment by KamiSami** [comment]
I can confirm this does not happen with requiem and pandemonium alone, not sure what mod could possibly be interfering with this... I did also notice i can't phase through blocks like before with those mods in my list. Let me see if logs say anything...

**Comment by KamiSami** [comment]
Nothing in logs at the time of testing to phase through floor or wall, same with possession and being attacked, i did notice husks did not aggro me when i was husk, but skeleton did try aggro me, but dropped aggro after second, and repeated that few times and managed shoot me once and i left the husk... Then it didn't aggro me anymore when i was wandering spirit, it seems they are buggy with their aggro when i possess something, the skeletons at least in that modpack.

**Comment by KamiSami** [comment]
Okay, something good came out from my testings, besmirchment (bewitchment addon) seems to cause inability to phase through walls and floor for some reason, as after removing it, im able to phase through walls and floors again. I don't know why though. I don't know if this is something that can be fixed on this side or besmirchment's side.

**Comment by KamiSami** [comment]
Okay last message for now unless more information required. And good this time too.

Found the cause! Okay, there is incompatibility with Gobber2 which causes some mobs aggro you even that you possess mobs! And incompatibility with besmirchment which causes inability to phase through blocks! I hope this information proves useful if there is way to make these mods compatible again. If there is anything else i can provide, do ask, i try remember to check here sometimes till this gets closed.

**Comment by Pyrofab** [comment]
Thanks for the info ! The besmirchment issue was already found out in #292, but I had never heard of the aggro bug Gobber2 so thanks for your investigation.

**Comment by Pyrofab** [comment]
After checking, I can't really do much about this. You'd have better luck reporting this to Gobber's mod author.

**Comment by KamiSami** [comment]
Alright, will do that.

**Comment by kwpugh** [comment]
Hi, I'm the author of Gobber.  What did you do to figure this out?

"Found the cause! Okay, there is incompatibility with Gobber2 which causes some mobs aggro you even that you possess mobs! "

**Comment by kwpugh** [comment]
Oh, I see the dumb mistake I made with the canTarget mixin into MobEntity

Simple fix now that I think about it in the context of your mod.

Will push a fix update to curse forge.

**Comment by Pyrofab** [comment]
Right, sorry I should have pointed to the source of the incompatibility when I looked it up. Glad you figured it out though !
By the way if it's not done yet I would recommend changing [this kind of code](https://github.com/kwpugh/gobber_fabric/blob/master/src/main/java/com/kwpugh/gobber2/mixin/MobEntityMixinCanTarget.java#L40-L47) - it prevents the next mixin from running entirely, so it would be better to first check if the desired value is actually different from the current value (`if (cir.getReturnValue() != desired) cir.setReturnValue(desired)`)
