### ISSUE TITLE
(Pandemonium) Chance to duplicate yourself when re-entering body if you somehow manage to dissociate more than once at the same time

### ISSUE THREAD

**Issue by xandercreates** [Ladysnake/Requiem#351]
There appears to be a chance for you to duplicate your player

How to reproduce: Seems to happen if you dissociate (and/or hold the dissociate key down) when you get a lag spike (FPS) and then re-enter your body, once you re-enter your body you will see a duplicate of yourself

![2021-06-07_11 29 57](https://user-images.githubusercontent.com/69139978/121047398-3abce300-c784-11eb-91d7-0e3e53ad4b24.png)
![2021-06-07_10 42 48](https://user-images.githubusercontent.com/69139978/121047460-3ee90080-c784-11eb-98ff-291142d9ac7c.png)

Mod Version: 1.7.11
Game Version: 1.16.5
Fabric Version: 0.11.3
Java Version: <Bundled Runtime, 8u51> (Strange, I thought I selected the jre i installed myself)
Windows 10

**Comment by Pyrofab** [comment]
I thought I fixed it but it seems I did a crucial mistake...
