### ISSUE TITLE
Players which are possessing a mob don't have a nametag above them

### ISSUE THREAD

**Issue by JumperREDACTED** [Ladysnake/Requiem#352]

**Comment by Pyrofab** [comment]
Sounds... normal ? Have you tried toggling the `requiem:showPossessorNametag` gamerule ?

**Comment by JumperREDACTED** [comment]
> Sounds... normal ? Have you tried toggling the `requiem:showPossessorNametag` gamerule ?

oh, missed the whole configuration portion on curseforge, nvm then, sorry about false alert
