### ISSUE TITLE
Feature: Requiem tag to only allow access to hotbar/offhand/armor but not rest of inventory.

### ISSUE THREAD

**Issue by James103** [Ladysnake/Requiem#361]
Currently, as shown by the available defined tags, there is no way to make it so while possessing a mob, you can use your main and offhand, hotbar, and possibly armor slots, but not the rest of the inventory. To fix this, I suggest adding in a tag, such as `#requiem:inventory/hotbar_only` or something similar. When an entity is in this tag, anyone possessing that entity can only use their main/offhand and hotbar slots, but the rest of their inventory would be blocked. If that entity also exists in `#requiem:inventory/armor_users`, the entity can use their armor slots as well.

I have a couple of ideas for the default contents, which could either be:
* Empty, preserving all default behavior from previous versions but still allowing customization as shown above
* Contains `minecraft:villager` and `minecraft:piglin` as both entities only have 8 hidden inventory slots when not being possessed, and limiting to hotbar only would be closest to that behavior.

**Comment by Pyrofab** [comment]
Sure, why not. We don't want to make villagers and piglins too annoying to play though, so first option sounds more likely.

**Comment by Pyrofab** [comment]
Fixed in 2.0.0-alpha.10 ☑
