### ISSUE TITLE
Witch kicks me out.

### ISSUE THREAD

**Issue by Pyronius1204** [Ladysnake/Requiem#364]
I turned myself into a zombie villager, and then cured myself to become a villager, and when I get struck by lightning, it does turn me into a witch, but it banishes me from the witch instantly. I can't repossess it and I have all my inventory with me even as the ghost, except I can't scroll through my hot bar or move things around, but I think that part is normal. It's just the witch kicking me out that is weird.

**Comment by Pyrofab** [comment]
Huh. Indeed, that sounds like a bug.

**Comment by ruan128** [comment]
same im not the owner i know how to fix that put in your possesable files the id minecraft:witch and pu the " like the villager

**Comment by Pyrofab** [comment]
I can't reproduce, does this happen with the latest version of Requiem ?

**Comment by Pyrofab** [comment]
Well, if you can reproduce this on the latest version, feel free to reopen
