### ISSUE TITLE
Requiem makes mobs move much faster

### ISSUE THREAD

**Issue by EddyHz** [Ladysnake/Requiem#371]
I'm not sure if this is an intended feature or a bug, but after installing Requiem, I noticed that mobs, specifically hostile mobs, move much much quicker than the usual pace.

**Comment by Pyrofab** [comment]
Ah, and they keep being faster even when not possessed ?

**Comment by James103** [comment]
You may want to issue the following command and then post the resulting log output:
`/execute as @e run attribute @s generic.movement_speed get`

**Comment by Pyrofab** [comment]
I'd really like to get more information on this issue, because there is nothing in Requiem that could speed up unpossessed mobs.

**Comment by Pyrofab** [comment]
Since I don't have anything to go off of to fix this bug, I'll go ahead and close this issue. Feel free to reopen it if you have more details.

**Comment by stormdirus2** [comment]
Actually I think I may have experienced this at one point.
It specifically happened after I set my soul state to false using commands while possessing a skeleton.
The skeleton moved much faster than I thought it would. Just might be me seeing things though.
