### ISSUE TITLE
Crash When Using the 1.17 Alpha Release

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Requiem#373]
I'm not sure if this is useful information to you, but I crash when loading the new alpha release for 1.17 (2.0.0-alpha.1)
I only have Requiem 2.0.0-alpha.1 and Fabric API 0.34.8+1.17 installed. I am using Java 16 installed from OpenJDK.

The crash log is at the following link:

https://paste.ee/p/ULuBe

Hope this is helpful, Requiem is probably my favorite mod :)

**Comment by ghost** [comment]
I am also using MultiMC launcher

**Comment by Pyrofab** [comment]
Thanks for the report and thanks for the kind words !

**Comment by Pyrofab** [comment]
Should be fixed now.
