### ISSUE TITLE
When I create a world and try to enter minecraft 1.17.1 crashes

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Requiem#375]
In the follder mods i have 3 mods its a requiem 2.0.0 alpha 2, requiem pandemonium 2.0.0 alpha 2, and fabric api 0.37.0 1.17
Minecraft Fabric Version: Fabric Loader 0.11.6 1.17.1
Crash Report: https://pastebin.com/0eytXSBj
What happened?: When i try create a world and enters to this world minecraft has been crashes (that happens in the any world)

**Comment by Pyrofab** [comment]
This crash should be fixed in alpha 3.
