### ISSUE TITLE
[1.17.1] Server Crash on launch

### ISSUE THREAD

**Issue by Matiam0** [Ladysnake/Requiem#377]
Not sure why it's crashing myself but i would rather report it just in case.
Using alpha-3 for the 1.17 version of requiem, single player works fine.

_java -version gives me_
`openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Microsoft-22300 (build 16.0.1+9)
OpenJDK 64-Bit Server VM Microsoft-22300 (build 16.0.1+9, mixed mode)`

[latest.log](https://github.com/Ladysnake/Requiem/files/6844230/latest.log)

**Comment by Pyrofab** [comment]
Ah, that was a very stupid error on my side. Will definitely be fixed for next alpha.

**Comment by Matiam0** [comment]
I can confirm this fix is working but for some reason we are unable to use the disassociation to leave the possessed body but we can work around that. ty!

**Comment by Pyrofab** [comment]
That part is normal unless you are talking about a golem - you need the Emancipation status effect now
