### ISSUE TITLE
1.17.1 requiem-2.0.0-alpha.3 "[Worker-Main-2/WARN]: Unable to load model"

### ISSUE THREAD

**Issue by WolfBV** [Ladysnake/Requiem#378]
[Worker-Main-2/WARN]: Unable to load model: 'requiem:block/tachylite/runic/attrition_on' referenced from: requiem:tachylite/runic/attrition#activated=true: java.io.FileNotFoundException: requiem:models/block/tachylite/runic/attrition_on.json

[Worker-Main-2/WARN]: Unable to load model: 'requiem:block/tachylite/runic/emancipation_on' referenced from: requiem:tachylite/runic/emancipation#activated=true: java.io.FileNotFoundException: requiem:models/block/tachylite/runic/emancipation_on.json

[Worker-Main-2/WARN]: Unable to load model: 'requiem:block/tachylite/runic/reclamation_on' referenced from: requiem:tachylite/runic/reclamation#activated=true: java.io.FileNotFoundException: requiem:models/block/tachylite/runic/reclamation_on.json

log while loading an instance, don't know if it matters

**Comment by Pyrofab** [comment]
Yeah that just means the model does not exist yet. Will be fixed in next alpha.
