### ISSUE TITLE
A bunch of bugs I've written down

### ISSUE THREAD

**Issue by Ironence** [Ladysnake/Requiem#38]
- [x] Incorrect sound upon blocking with shield while possessing a mob (Uses the possessed mob's damage sound, not the shield sound).

- [x] Items in off-hand rendered incorrectly while possesing any mob.

- [x] Player can still take damage while possessing a mob in Creative Mode, albiet the health bar is not shown.

- [x] Dying while possessing something in Creative mode crashes the game. For obvious reasons.

- [x] Possessed mobs fail to play attacking animation in Third Person.

- [x] Skeleton/Wither Skeletons block with a shield really awkwardly. Zombies block awkwardly, too, but to a lesser degree (No effect on gameplay, by the way. Just the Animations.)

- [x] Zombie villagers turn into regular zombies when possessed.

- [x] Helmet fails to break from sunlight damage while possessed (Repeatedly plays breaking sound).

- [x] Baby Zombies catch fire when possessed.

- [x] Skeletons can hit themselves when using a Bow.

- [x] Crouching while in Creative mode crashes the game (Dismounts the mob, which is not normally possible in Survival).

- [x] Camera vibrates when walking into a head-level block while possessing Wither.

- [x] Villagers don't run away from possessed Zombies.

- [x] Looking around quickly while possessing a mob lags the game slightly.

- [x] Eating/Drinking animation is REALLY fast for some reason while possessing a mob.

- [x] Villagers killed by a possessed zombie will not turn into a Zombie Villager.

- [x] Fire (While the player is on fire) will flicker while possessing a mob with Fire Resistance.

- [x] Leaving a world as a spirit will hide the hotbar upon joining another world where you're not dead.

- [x] Getting purified will sometimes gets the player stuck in the death animation. Fixes itself upon re-joining the game.

- [x] The Player isn't shown in the Inventory screen when possessing a Mob.

- [x] Potions will occasionally appear completley black in the Inventory while possessing mob (Maybe enchanted items too. Haven't tested that yet).

- [x] Unable to fly in creative mode while possessing a mob.

If any of these need clarity, I'll try to make it more clear.

**Comment by Pyrofab** [comment]
Thanks a *ton* for the cooperation, most of these are fixed in Dissolution Resurrection. The others are generally minor issues.

**Comment by Pyrofab** [comment]
Oh wow, I can finally resolve this issue ! Everything that was left is solved in 1.14.
