### ISSUE TITLE
Suggestion (Pandemonium) Enter Beehives as a bee

### ISSUE THREAD

**Issue by bugsarerules** [Ladysnake/Requiem#380]
This may be a hard one, but I would like to see if it could be possible to enter a beehive as a bee, and as you are inside, you can sleep just like in a bed.
Or when you enter, you enter a beehive-like structure like a teleport
It's gonna be a disaster for you guys to code this, but I think it would be a fun idea

**Comment by Pyrofab** [comment]
There is already Bumblezone compatibility for bees: click on a beehive with that mod installed and you go to that dimension. I think this fits the criteria well enough ?

**Comment by Pyrofab** [comment]
I'll consider this already done.
