### ISSUE TITLE
Survival Players can Fly when possessing a shell

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Requiem#381]
In the beta.6 1.17 version of the mod, I have found that I can fly in survival if I possess a summoned player shell, I tried switching to creative and then back to survival and I still had the ability to fly as a normal player.

I was playing around with obelisks before this, but I don't think that's related

Hope this helps! And thanks for the awesome mod

**Comment by TheBrogan101** [comment]
You also can’t take damage

**Comment by Pyrofab** [comment]
What exactly did you do to trigger this ? How did you summon the shell ?

**Comment by piouplouf** [comment]
it also happen in 1.16.5 version with pandemonium installed. when you're a ghost and you type "/requiem shell create @s", the shell created is invulnerable and can fly. the shell bcome normal again when reloading the save while possessing it

**Comment by ghost** [comment]
I summoned the shell with the `/requiem shell create` command, I also used emancipation to create a shell in a survival friendly way, both the shells were invulnerable when possessed, I did not check their vulnerability when not possessed

The world I was in was a creative world, but I was in survival when I summoned the shells

**Comment by Pyrofab** [comment]
Weird, I don't get this. Does it happen with no other mod ?

**Comment by ghost** [comment]
> it also happen in 1.16.5 version with pandemonium installed. when you're a ghost and you type "/requiem shell create @s", the shell created is invulnerable and can fly. the shell bcome normal again when reloading the save while possessing it

I have also found this to be the case.
Steps to reproduce:
1) Have a new instance of Minecraft with only Requiem Alpha.6 and Fabric API installed
2) Create a new world with cheats enabled
3) Die to enable Requiem (/kill is fine)
4) Go through the dialogue screens to become a demon
5) Run `/requiem shell create @s`
6) Possess the shell that was produced

This will allow you to fly and be immune to damage as if you are in creative mode (you can still die to the void, it just turns you back into a spirit as if you had died in survival.)

The only way to reverse these effects is to relog, on relogging, you will essentially be a normal survival player again, but with one level of attrition that will wear off as if you had cured yourself from undead.

Hope this clears it up!

**Comment by ghost** [comment]
Update: This bug is still in Alpha 10, the results are exactly the same

**Comment by ghost** [comment]
Another Update: Mobs also don't aggro on a player possessing a shell, just like if the player were in creative mode

**Comment by Pyrofab** [comment]
Thanks for the details ! Should be quite helpful.

**Comment by ComradeBlue1337** [comment]
I know this post is quite old now but still, i was testing the Alpha 12 version and this bug is still there by the way.
And also, summoned shells do not suffocated underwater, are unable to place blocks too, and also the only way to fix this issue currently is to leave and rejoin your world.

**Comment by Pyrofab** [comment]
This should be fixed in 2.0.0 alpha 12, feel free to reopen if that's not the case.
