### ISSUE TITLE
when you remove a mod that you put a mob id to posses you cant posses until remove the mob id from possesable.json file

### ISSUE THREAD

**Issue by ruan128** [Ladysnake/Requiem#382]
make so when you remove a mod with the mob id in possesables.json the mod still works ignoring that theres a id that dont exist

**Comment by Pyrofab** [comment]
You can already do that by using `{"id": "themod:themob", "required": false}` instead of `"themod:themob` ^^'

**Comment by ruan128** [comment]
ok thanks
