### ISSUE TITLE
Bug: Can't right-click mobs with 1.17 alpha 8 (requiem-2.0.0-alpha.8.jar)

### ISSUE THREAD

**Issue by Dual-Iron** [Ladysnake/Requiem#385]
For example, right-clicking a horse (with or without an item in your hand) does nothing.

Bloodsucking from haema works fine--the binding is shift-rightclick--but simply right-clicking entities does nothing but play the swinging arm animation on the player.

**Comment by Pyrofab** [comment]
Thanks for the report ! Should be fixed in alpha 9.
