### ISSUE TITLE
Attrition does not increase on host death and HOST_DEATH event does not fire

### ISSUE THREAD

**Issue by stormdirus2** [Ladysnake/Requiem#388]
Steps to reproduce Attrition bug:
* Create a new world (with cheats)
* run /kill
* Become remnant
* Summon skeleton and possess it
* Let yourself die to fire damage
--> Doesn't upgrade your Attrition.

Steps to reproduce HOST_DEATH not firing:
* Hook into the HOST_DEATH event on initialization
* Add a System.out.println or something
--> It will not print anything

**Comment by Pyrofab** [comment]
Fixed in alpha 10 ☑
