### ISSUE TITLE
dissociation not working with some mobs

### ISSUE THREAD

**Issue by Sasson100** [Ladysnake/Requiem#390]
sometimes the dissociation button (the button that lets you go out of a body without killing yourself or being killed) doesn't work with some of the mobs (for example: it works with the iron golem, but it doesn't with the husk)

**Comment by Pyrofab** [comment]
Sounds like it works as intended. Golems are completely frictionless, they do not interact with souls and so you can enter and leave them as you wish. Undead however keep your soul in when you possess them, so you cannot dissociate as easily. In future versions (2.0.0) you will be able to leave without dying by using the new Emancipation effect.

**Comment by Sasson100** [comment]
ok, i didn't know about that, and I didn't find anything about this in the requiem wiki, so I thought it wasn't working properly

**Comment by Pyrofab** [comment]
Ah, yeah we may be falling behind on documentation. We'll try to improve that.
