### ISSUE TITLE
requiem-1.7.13 and Age of Exile 2.1.5 Can't gain Combat Experience when possessing mob

### ISSUE THREAD

**Issue by Lightveld** [Ladysnake/Requiem#393]
When possessing a mob while playing in a pack with both Age of Exile and Requiem, you can't get experience for Age of Exile from kills, even with Humanity enchants, experience works just fine from the Divine Mission Shrines.

Currently have an Issue open with the Age of Exile dev who wants to know if you have any Ideas on what should be done.

https://github.com/RobertSkalko/Age-of-Exile/issues/132

**Comment by Redfan2** [comment]
This issue will be closed as Age of Exile hasn't been updated since 1.16.5. This issue is no longer relevant as Requiem won't fix bugs on outdated versions.
