### ISSUE TITLE
Requiem Crashes with Resource Packs from lower Minecraft versions.

### ISSUE THREAD

**Issue by KirbyKid256** [Ladysnake/Requiem#395]
Hi, I've been having a problem trying to load a resource pack so I could integrate Requiem as an addon. Specifically the "Minecraft - Super Mario Bros. Edition 1.16 v1.4" pack. I think it's due to the fact that it's for a lower version of Minecraft since resource packs for 1.17 work just fine.
[crash-2021-08-15_19.51.54-client.txt](https://github.com/Ladysnake/Requiem/files/6989081/crash-2021-08-15_19.51.54-client.txt)

**Comment by Pyrofab** [comment]
Ehm, your resource pack packages an old version of minecraft shaders for whatever reason. I don't think I can do much about that.

**Comment by KirbyKid256** [comment]
Got it. I was able to fix it by removing the shaders from the resource pack. Thanks anyways.
