### ISSUE TITLE
How do i use Optifabric with Requiem?

### ISSUE THREAD

**Issue by Begnom** [Ladysnake/Requiem#396]
I get this error message when trying to use both these mods:

Found conflicting mods: requiem conflicts with {optifabric @ [*]}
Creating Empty clause ?

Anyone knows why this happens or the solution to this error?

**Comment by stormdirus2** [comment]
You don't.

**Comment by stormdirus2** [comment]
Optifabric is bad, always has been. Use Iris or Canvas instead. These mods conflict, that's why it won't let you start the game

**Comment by Begnom** [comment]
Well i know that i could use Iris or Canvas, but i still want to use shaders. Is there some mod that could allow me to use shaders without optifine and on Fabric?

**Comment by stormdirus2** [comment]
> Well i know that i could use Iris or Canvas, but i still want to use shaders. Is there some mod that could allow me to use shaders without optifine and on Fabric?

Yes, Iris and Canvas.
