### ISSUE TITLE
Server crashes when joining ( after data sync ) [ 1.17.1 ] v2.0.0-alpha.10

### ISSUE THREAD

**Issue by Korinku** [Ladysnake/Requiem#397]
So, the server starts fine, everything is working until some player joins, then the requiem tries to sync the data and the server crashes.

**LOG**
https://hastebin.com/raw/salonayici

**Comment by Korinku** [comment]
in-game:

https://user-images.githubusercontent.com/33789496/130267112-301a7f4c-ff04-4a6f-bcd6-d2773edab906.mp4

**Comment by Pyrofab** [comment]
Thanks for the detailed report ! I think I know what's happening, should be relatively easy to fix.

**Comment by Pyrofab** [comment]
Should be fixed in alpha 11
