### ISSUE TITLE
AI issues / Soulless mob inconsistency

### ISSUE THREAD

**Issue by ComradeBlue1337** [Ladysnake/Requiem#420]
Soulless villagers who were zombified do not have AI if you leave the body while Players who were killed by zombies and zombified will still have AI.

**Comment by ComradeBlue1337** [comment]
Extra details: A similar issue happens when you cure a zombie piglin and then leave the cured piglin's body. it will have AI.

And as the cured body isnt undead, it isnt supposed to be moving around aswell.

**Comment by Pyrofab** [comment]
Zombie villagers should now be fixed. Cured zombies moving around normally is a vanilla feature though.
