### ISSUE TITLE
Souls return to bodies that already have one

### ISSUE THREAD

**Issue by ComradeBlue1337** [Ladysnake/Requiem#430]
Souls return to bodies that already have player souls on them.
Example: I stole a piglin's soul and possessed the body and then used the filled soul vessel and released the soul, then the soul simply came back to the body causing 2 souls to be in the same body.

The soul should just vanish instead right?

**Comment by ComradeBlue1337** [comment]
Note: And when leaving the body, it will have AI.

**Comment by Pyrofab** [comment]
Sounds like intended behaviour :)
