### ISSUE TITLE
Player shell inconsistency

### ISSUE THREAD

**Issue by ComradeBlue1337** [Ladysnake/Requiem#432]
You shouldnt receive attrition for killing your player shell when not possessing it.
Or should you?
Like imagine leaving your player shell and then a mob kills it and you just happen to gain attrition for that.

I know player shells work differently than mob shells like, they drop XP when killed and stuff but still.

**Comment by Pyrofab** [comment]
Right, this was added because in pandemonium your soul kept a strong link to your shell, but it's not really justified now.
