### ISSUE TITLE
Requiem glowing runed textures not working

### ISSUE THREAD

**Issue by Sigma100001** [Ladysnake/Requiem#434]
The textures do not show when you build the tower.  It happens for every runed texture
![textures not working](https://user-images.githubusercontent.com/81214241/136464510-b833c38c-a7fd-41f6-9780-45b8e361b07a.png)

**Comment by Pyrofab** [comment]
Which version of requiem are you using, and with which mods ?

**Comment by Sigma100001** [comment]
requiem 2.0.0 alpha 13

**Comment by Sigma100001** [comment]
I am using Iris shaders so that might be an issue

**Comment by Sigma100001** [comment]
yeah iris and requiem are slightly incompatible

**Comment by Pyrofab** [comment]
More like sodium, but yeah. You should be able to install indium as a workaround I believe.

**Comment by Pyrofab** [comment]
Noted the incompatibility on the curseforge page, It think that's all I can do really.
