### ISSUE TITLE
NullPointerException when join world

### ISSUE THREAD

**Issue by SettingDust** [Ladysnake/Requiem#436]
1.17.1 

Only requiem and fabric api in mods

https://gist.github.com/SettingDust/569ddf4334caf50499f0070a012c72be

**Comment by Pyrofab** [comment]
What the fuck

**Comment by SettingDust** [comment]
> 
> 
> What the fuck

The "fuck" is the newer fabric. I update the fabric-api and fabric-loader in Gradle to 0.12.2 and 0.41.0+1.17. It's appeared. Need to test for exact version.

Edit:
0.12.0, 0.12.1 can't startup game. 0.12.2 can't join world. 0.11.7 is ok

Due to https://github.com/FabricMC/Mixin/commit/24faba3496419acbff7c113cc2234f73618c3a82. The 0.12.0/1 error caused by a bug of mixin. The 0.12.2 fixed it (Update mixin)

Fabric loader changes: https://github.com/FabricMC/fabric-loader/compare/8879128ed5a9b29f84c7a1272e0de75ab282a5bf...master
In these changes, mixin update from `0.9.3+mixin.0.8.2` to `0.10.3+mixin.0.8.4`

Mixin changes: https://github.com/FabricMC/Mixin/compare/11ec11c5f17e344e4810680bdd8bea0fed17ce5b...FabricMC:main

I think it's in [`11ec11c5f17e344e4810680bdd8bea0fed17ce5b...main`#diff-3ad778b7c9](https://github.com/FabricMC/Mixin/compare/11ec11c5f17e344e4810680bdd8bea0fed17ce5b...main#diff-3ad778b7c95a0d71f95d7c67d4f272e305528c4cde27e79426a719e0c83a97e2)

**Comment by Pyrofab** [comment]
Right, it was linked to the mixin update... still, null callbackinfos ? Anyway, thanks for the details, I'll try to fix it.

**Comment by Pyrofab** [comment]
Ok I think I found what the fuck was, could you try updating to fabric loader 0.12.3 ?

**Comment by SettingDust** [comment]
> 
> 
> Ok I think I found what the fuck was, could you try updating to fabric loader 0.12.3 ?

Same result

**Comment by Pyrofab** [comment]
Oh well, would have been too easy I guess

**Comment by Pyrofab** [comment]
Now, could you try Fabric Loader 0.12.5 ?

**Comment by SettingDust** [comment]
> 
> 
> Now, could you try Fabric Loader 0.12.5 ?

I will try later

Edit: @Pyrofab It's ok now!
