### ISSUE TITLE
Mobs Attack After Bumping Into Them While Possessing

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Requiem#438]
Directly after bumping into a mob while possessing one, all nearby mobs will aggro towards the player. At first I thought this was a glitch with other mods, but after leaving only fabric api and the mod itself in the folder it continues to happen. I do not know if this is intended since I haven't found any documentation on it. If it is intended, "Apologies in advance!"

**Comment by ghost** [comment]
A link to gameplay of the possible issue: https://youtu.be/KrD-p0d33Hc

**Comment by Arathain** [comment]
"It's not a bug, it's a feature."
basically, intended

**Comment by ghost** [comment]
Okay, at least I know now (I shall wait for any developer to close the thread). But besides that, when the mobs keep firing after the player has died already is definitely a bug.

**Comment by Pyrofab** [comment]
Which version is that ? In the latest alpha only the mob who you bumped into should aggro, and the firing after death issue should be fixed.

**Comment by ghost** [comment]
This was in 2.0.0alpha12. So it Might be outdated, but I can test real quick.

**Comment by Pyrofab** [comment]
Yeah, the feature was added in alpha 12 and we got bug reports that were fixed in alpha 13.
