### ISSUE TITLE
Pandemonium Possession of Chickens Allows Flight

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Requiem#439]
When possessing  a chicken you can fly up and down with space and shift. It isn't like creative flight is is more similar to spectator flight. I do not think this was in the later versions and I wanted to document it. Thanks!

Video Of the issue: 
https://youtu.be/_geC4RtLQnQ

(I can't send it normally and I have to upload it to YouTube first)

I apologies if this is intended!

**Comment by LordDecay26** [comment]
oh my god that's hilarious

**Comment by Pyrofab** [comment]
Can't reproduce it myself... Does this happen with only requiem installed ?

**Comment by Pyrofab** [comment]
Thanks for the report, I managed to reproduce it and provide a fix in 2.0.0-beta.11
