### ISSUE TITLE
"Mobs can now become hostile if you come too close ! "Can you make an option to switch it on and off? 

### ISSUE THREAD

**Issue by aeswda** [Ladysnake/Requiem#441]
"Mobs can now become hostile if you come too close ! "Can you make an option to switch it on and off? I prefer the previous mechanism

(this passage is translated by machine and may have errors, including this sentence, sorry)

**Comment by Pyrofab** [comment]
Something like `requiem:possessionDetection` ? https://ladysnake.github.io/wiki/requiem/configuration#gamerules (not released yet, will come with next alpha)

**Comment by James103** [comment]
> Something like `requiem:possessionDetection` ? https://ladysnake.github.io/wiki/requiem/configuration#gamerules (not released yet, will come with next alpha)

The gamerule is now available as of the thirteenth alpha for 2.0.0.

**Comment by Pyrofab** [comment]
Right, the website has been updated, so I guess this issue can be closed
