### ISSUE TITLE
Unable to load up worlds

### ISSUE THREAD

**Issue by LiviiYS** [Ladysnake/Requiem#442]
Game starts up but when i try to load up a world new or old I get an issue about not being able to load villager diet

https://gist.githubusercontent.com/LiviiYS/49ff6c76521958f897a6e0112403b892/raw/f1450fc583ead06d5f71554d2141d2c3a81dcad7/gistfile1.txt

**Comment by Pyrofab** [comment]
Right, try using Fabric Loader 0.11 instead
