### ISSUE TITLE
requiem-1.7.15 Crashing on startup (Fabric loader 0.12.5)

### ISSUE THREAD

**Issue by Fade-Alchemist** [Ladysnake/Requiem#444]
Failure to launch, I am using Fabric Loader version 0.12.5 and requiem-1.7.15.jar.  I also did tests isolating one mod at a time. 
[latest.log](https://github.com/Ladysnake/Requiem/files/7539860/latest.log)

[crash-2021-11-15_10.49.49-client.txt](https://github.com/Ladysnake/Requiem/files/7540288/crash-2021-11-15_10.49.49-client.txt)

**Comment by Pyrofab** [comment]
So ehm, what's the minimal set of mods with which you can reproduce this issue ?

**Comment by ruan128** [comment]
me launcher always crash on version above 1.20 so i guess its not a mod problem and yes fabric or lancher so ye fade try using requiem 1.7.14
