### ISSUE TITLE
suggestion:when mobs killed they drop a dead body that can be posses without modifing any file on the mod

### ISSUE THREAD

**Issue by ruan128** [Ladysnake/Requiem#445]
well i think that would kinda make sense

**Comment by Pyrofab** [comment]
Did you look at soul vessels yet ?

**Comment by ruan128** [comment]
nope

**Comment by ruan128** [comment]
but im playing with pandemonium like always

**Comment by Pyrofab** [comment]
yes well, pandemonium has been more or less merged in Requiem 2.0. We will be covering this stuff in the wiki soon, but the short version is: you can take a mob's soul away with a soul vessel, and then you can possess that empty shell.

**Comment by ruan128** [comment]
also the issue of the user that tells that he crashes when using the 2nd newest verison (im lazy to look) is because fabric 1.20 and above is crashing on some launchers (i dont know if its all of the launchers)

**Comment by Pyrofab** [comment]
well, guess I'll be closing both those issues then, feel free to reopen if I'm missing something.

**Comment by ruan128** [comment]
ok
