### ISSUE TITLE
Suggestion/enhancement: Allow the possession of sleeping players

### ISSUE THREAD

**Issue by LordDecay26** [Ladysnake/Requiem#448]
allowing a demon to posses a sleeping player would be cool. this could force the player out of their body and into soul form, and allow the demon to take on the identity of the player who's sleeping body they stole. (the SHENANIGANS)

This would obviously need some sort of counter, like something you put in your inventory like a talisman or sage or something, i'll leave it up to you, but it would be a really cool mechanic which fits in with the original folklore regarding demons.

**Comment by Pyrofab** [comment]
I don't think we want to add that to the base mod, maybe an addon could use that idea one day though.

**Comment by LordDecay26** [comment]
maybe, but i thought of a counter.
you should only be able to be possessed if you have insomnia (phantoms can spawn)
makes sense in the context of the game, and balanced because all you gotta do to prevent possession if sleep

**Comment by Pyrofab** [comment]
Going to close this as I don't think this will happen in the base mod. Thanks for having taken the time to make this suggestion though 👍
