### ISSUE TITLE
2 compatibility issues with bewitchment

### ISSUE THREAD

**Issue by enderman712** [Ladysnake/Requiem#450]
one causes you to start looking for an undead body to possess if you die with a death protection poppet in your inventory

another is that when you go into the state of looking for a new body your transformation is set to human

I understand that it could be either mod please let me know if and when you are working on a fix

(if you need to take your time, do so)

**Comment by Pyrofab** [comment]
First thing sounds like an ordering issue, shouldn't be too hard to fix. For the second one, do you mean your transformation is forever lost when you die with requiem, or it's just lost for as long as you are a ghost ?

**Comment by Pyrofab** [comment]
Closing this issue as the current version of Bewitchment has been discontinued
