### ISSUE TITLE
Issue with possession of giants

### ISSUE THREAD

**Issue by enderman712** [Ladysnake/Requiem#451]
when I tried to posses a giant it would do the fov effect on everything around me but I wouldn't posses the giant, instead it would lock me in the wandering state.

I only tried this because I have a mod that gives giants ai

**Comment by Pyrofab** [comment]
does this happen if you try to possess a giant in vanilla too ?

**Comment by Asteroid4** [comment]
It does not. I have tried it.

**Comment by Pyrofab** [comment]
so, this is a mod compatibility issue right ? Which mod is it failing with ?

**Comment by Pyrofab** [comment]
Closing this as missing the information required to fix.
