### ISSUE TITLE
could i upload the chinese language

### ISSUE THREAD

**Issue by IceBingQI** [Ladysnake/Requiem#452]
I translated it into Chinese，I like this mod very much，I hope Chinese people can understand it。This is link https://drive.google.com/file/d/1KZP_j4VvvN79hTELaUaYu2c2HyAkzeqv/view?usp=sharing

**Comment by Pyrofab** [comment]
Thanks! May I suggest opening a pull request for this?

**Comment by IceBingQI** [comment]
> Thanks! May I suggest opening a pull request for this?

OK I think you can opening a pull request

**Comment by IceBingQI** [comment]
> 谢谢！我是否可以建议为此打开拉取请求？

OK I have done pull requests

**Comment by IceBingQI** [comment]
I have done pull requests，could you agree it？

> Thanks! May I suggest opening a pull request for this?

**Comment by Pyrofab** [comment]
Oh, yes thank you for the reminder ! It's done now.
