### ISSUE TITLE
Crash on startup with 2.0.0-beta.2

### ISSUE THREAD

**Issue by AeiouEnigma** [Ladysnake/Requiem#456]
[latest.log (pastebin)](https://pastebin.com/qSqSAeq0)

I'm using the latest version of Requiem and its dependencies, with no other mods. I wish I had more to say about the issue, but all I can tell is that there's some sort of mixin application error.

Thank you for your help. I'm very excited to try your mod :)

**Comment by ACrazyD** [comment]
Can confirm this issue, However i have a few more mods then just Requiem + Dependencies.

Hope another log will help you find the issue fast
[latest.log](https://github.com/Ladysnake/Requiem/files/7670755/latest.log)

**Comment by Urkaz** [comment]
Same crash here using only Requiem 2.0.0-beta.2 and fabric-api 0.44.0+1.18. Seems a 100% ratio.

**Comment by Pyrofab** [comment]
Thanks ! The issue has been identified and is fixed for next beta.

**Comment by Pyrofab** [comment]
Fixed in beta 3
