### ISSUE TITLE
[2.0.0-beta2] Crash on startup

### ISSUE THREAD

**Issue by mosharky** [Ladysnake/Requiem#459]
I don't really understand whats causing this, but a bunch of mixins are failing to apply

[https://pastebin.com/SKkbSzFY](url)

`[14:58:01] [main/ERROR]: Mixin apply for mod requiem failed mixins.requiem.client.json:inventory.InventoryScreenMixin -> net.minecraft.class_490: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on repositionCraftingButton could not find any targets matching 'm_ekzothcc' in net.minecraft.class_490. Using refmap requiem-refmap.json Method is @Dynamic(Lambda method, implementation of PressAction for the crafting book button). [PREINJECT Applicator Phase -> mixins.requiem.client.json:inventory.InventoryScreenMixin -> Prepare Injections ->  -> handler$doc001$repositionCraftingButton(Lnet/minecraft/class_4185;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]`

**Comment by Pyrofab** [comment]
Thank you for the report, this has been fixed in beta 3.
