### ISSUE TITLE
When on a multiplayer server with requiem on 1.18, villagers seem to be uninteractable

### ISSUE THREAD

**Issue by flashgnash** [Ladysnake/Requiem#461]
Right clicking villagers while possessing a mob will still play the hand animation but doesn't open the trade window, doing it unpossessed does nothing at all, the same goes for the Mortician.

Mods:
![image](https://user-images.githubusercontent.com/12749214/145979464-b30671b8-8c4e-4b61-8b4f-df2486d243d9.png)

(this includes trading post, as the client will start up with it but the server will not, however the issue still persists without it) 

When attempting to add the Trading Post mod to get around this (https://www.curseforge.com/minecraft/mc-mods/trading-post-fabric/) the server will not start up at all.

Can't do any more investigation right now but if I find anything else later I'll update this

**Comment by AITYunivers** [comment]
I have the same issue.

**Comment by Pyrofab** [comment]
Should have been fixed in 2.0.0-beta 5.
