### ISSUE TITLE
Requiem prevents server and client from starting.

### ISSUE THREAD

**Issue by AITYunivers** [Ladysnake/Requiem#462]
[Console Log](https://www.toptal.com/developers/hastebin/jolugifipu.properties)

Mod List:
![image](https://user-images.githubusercontent.com/92553545/146815987-a7f77a77-960f-40da-92a4-514267e0ff69.png)

**Comment by AITYunivers** [comment]
It crashes the client too
![image](https://user-images.githubusercontent.com/92553545/146816450-3362ba82-01fc-4c2f-9831-54313dae157a.png)

**Comment by Pyrofab** [comment]
Thanks for the report ! This build issue should be fixed in 2.0.0-beta.5

**Comment by AITYunivers** [comment]
This issue is ON beta 5

**Comment by Pyrofab** [comment]
The error clearly says beta.4 though

**Comment by AITYunivers** [comment]
Oh, well it still doesn't work on beta 5 either way.
