### ISSUE TITLE
Crashes when I try to open inventory or possess a target while dead.

### ISSUE THREAD

**Issue by GorinichSerpant** [Ladysnake/Requiem#464]
I installed the Light Craft modpack, as well as Requiem 2.0.0-beta5 and Chest Cavity 2.13.5 and when I attempted to open my inventory or possess an iron golem while a ghost it would crash the game. It didn't crash when I attempted to possess a sheep, which likely makes sense which I think means the game is crashing whenever I interact with anything as a ghost. Either way, here is a crash report I got from this.
[JKrzQBGds3.pdf](https://github.com/Ladysnake/Requiem/files/7773906/JKrzQBGds3.pdf)

**Comment by Pyrofab** [comment]
Duplicate of #465
