### ISSUE TITLE
Issues with Iris shaders and Requiem

### ISSUE THREAD

**Issue by TheGhostl** [Ladysnake/Requiem#465]
I made a new world and tried to play as a demon but i can't leave my body and if i die it crashes.
This si the log i get with crashy.
![Screenshot_4](https://user-images.githubusercontent.com/96665564/147392891-d7e48041-b0ae-4a7a-9ea7-e4480a5b63aa.png)

**Comment by TheGhostl** [comment]
I forgot to mention this is on update 1.18 so requiem-2.0.0-beta.5.jar

**Comment by Pyrofab** [comment]
Thanks for the report, Satin incompatibility with Iris should be fixed since a few versions ago.
