### ISSUE TITLE
Advancement announced in chat every time I disocciate from human body

### ISSUE THREAD

**Issue by AeiouEnigma** [Ladysnake/Requiem#467]
Every time I disassociate from my human body, an announcement is made in chat that I've again made the advancement [A devilish conundrum].

**Comment by Pyrofab** [comment]
Does this happen without other mods ? Which version are you using ?

**Comment by AeiouEnigma** [comment]
I tested with only Requiem 1.18.1 beta 5. No other mods were used.

**Comment by Asteroid4** [comment]
Same

**Comment by James103** [comment]
Are you somehow revoking the advancement anywhere at any time? If so, that may be what's causing this issue.

**Comment by AeiouEnigma** [comment]
Or it could be that the shell Player is spawned without the original Player's advancements, and the shell is awarded the advancement when the Player disassociates from it.

**Comment by Pyrofab** [comment]
This has been fixed, shells do not broadcast advancements as of a few beta versions ago.
