### ISSUE TITLE
Can't use soul rift

### ISSUE THREAD

**Issue by LeeSpork** [Ladysnake/Requiem#469]
When I hover my crosshair over the soul rift block, it shows an icon for entering it regardless of if I am dissociated or not.

When I click it, nothing happens (in either form). (I tried it both as part of an active obelisk and on its own).

Also, question, will it work trans-dimensionally? (e.g. between an obelisk in the nether and in the overworld)? Because in the screenshots I only noticed they were only identified by X/Y/Z co-ords.

My mods folder:
![image](https://user-images.githubusercontent.com/24984194/147861574-784067a2-06e4-420f-8f87-aab5c6d333f6.png)

**Comment by Xiribidus** [comment]
Afaik it does not work across dimensions. Assuming you do not have Attrition 4 I think one explanation might be a bug I encountered earlier, try putting the Rift as the bottom rune or in a seperate Obelisk and make sure you have enough soul blocks!

**Comment by Pyrofab** [comment]
The icon showing whether you are dissociated or not is a bug, will be fixed in next beta. For the rest, refer to xiri's answers.

**Comment by Pyrofab** [comment]
Rifts issues should be fixed now.
