### ISSUE TITLE
Compatibility Issue with certain mods(?)

### ISSUE THREAD

**Issue by NotAPotter** [Ladysnake/Requiem#470]
Doing some testing, I was unable to possess a zombie from the Zombified mod, but that may be more a problem with the other mod than this. But in the Super Block World mod, taking the soul of a goomba with an empty vessel worked fine, but crashed the game when i tried to possess it.

If it helps, the latter involved a portal that seemed to destroy the animal mob body i was occupying.

**Comment by Pyrofab** [comment]
May I see the crash report ?

**Comment by NotAPotter** [comment]
[crash-2022-01-01_20.58.24-server.txt](https://github.com/Ladysnake/Requiem/files/7803192/crash-2022-01-01_20.58.24-server.txt)

**Comment by Pyrofab** [comment]
Thanks for the report ! This looks like an issue in the Super Block World mod though.
