### ISSUE TITLE
Various Strange Behaviours With Origins Installed

### ISSUE THREAD

**Issue by Baryons314** [Ladysnake/Requiem#471]
Dissociating from your shell, without actually dying, will let you keep abilities of your Origin? For example, if you were a Phantom, you will be able to activate your ability to phase through blocks, and as a Merling, you will be able to see clearly in water.
In addition, when you have chosen a new origin with an orb of origin, being in spirit mode and creating a new shell will lead to the shell being of the old origin (which means if your old origin was Phantom, it will be invisible, and if you possess that body you will become a phantom.
Phantom shells will be invisible upon creation, but I believe this is intended- when a Phantom player spawns in, they are in their phantom phasing mode to protect against sunlight, which helps ensure the shell doesn't die. However, it may be worth noting.
Doing some testing, changing my origin to Enderian, then using /kill, my activated ability as a spirit is now the Phantom's phasing ability, which was my first origin.

**Comment by Pyrofab** [comment]
Thanks for the report, this should be fixed in beta 11.
