### ISSUE TITLE
My game crashed after I was killed by and enderman it said requiem, Iris and Satin were potential causes.

### ISSUE THREAD

**Issue by Shadowdragon3456** [Ladysnake/Requiem#472]
https://bytebin.lucko.me/Nz8tRK7zbW
version 1.18.1

**Comment by bytebone** [comment]
i had the same crash, though not by being killed but falling by fall damage. first error message appears the same - something with iris. 

MC Fabric 1.18.1
Requiem 2.0.0 beta 5

[crash-2022-01-10_16.48.13-client.txt](https://github.com/Ladysnake/Requiem/files/7840056/crash-2022-01-10_16.48.13-client.txt)

**Comment by Pyrofab** [comment]
This should be fixed in beta 6, or alternatively by manually installing the latest version of Satin.
