### ISSUE TITLE
Can't sleep in my world because of my vessels 

### ISSUE THREAD

**Issue by Dartttt** [Ladysnake/Requiem#474]
I can't sleep in my server because of the hollow vessels I made and left in the overworld, I don't know if this is intentional or not but it kinda sucks. It says it need 4 people to pass the night but theres only me and my friend on the server and I have 2 vessels that I've kept.

**Comment by Pyrofab** [comment]
Does this happen with no other mods than requiem ?

**Comment by Dartttt** [comment]
it only happens while i have vessels, i have a datapack which tells how many people need to sleep and it counts the vessels as actual players

**Comment by Pyrofab** [comment]
Should be fixed since a few beta versions ago.
