### ISSUE TITLE
Possessed mobs being able to target themselves causes undefined behavior with other mods

### ISSUE THREAD

**Issue by stormdirus2** [Ladysnake/Requiem#476]
Related issue: stormdirus2/nox#3

~~Pyrofab how did you even manage to do this.~~

**Comment by stormdirus2** [comment]
It has come to my attention that the reason possessed mobs can target themselves, is so that Zombified Piglins can attack themselves, correct?

Due to the potential issue with other mods, especially those that would compare the targets of 2 mobs (like mine), I suggest you restrict mobs targeting themselves to only that specific instance.

**Comment by PsychoBreadstick** [comment]
Seemingly fixed in a recent update.
