### ISSUE TITLE
Permanent redness w/ Entity Culling after possessed mob is damaged

### ISSUE THREAD

**Issue by AeiouEnigma** [Ladysnake/Requiem#477]
Clone of https://github.com/tr7zw/EntityCulling/issues/48

When using Entity Culling and Requiem, player-possessed mobs become permanently red-colored after taking damage, instead of only being red for the moment when they receive damage.
![image](https://user-images.githubusercontent.com/3160746/148703340-c3ea9734-eb63-4f41-ab5d-1e73b09e5c2f.png)

**Comment by tr7zw** [comment]
Fixed on my end.
