### ISSUE TITLE
Odd targeting behaviors from (semi-neutral) hostile mobs

### ISSUE THREAD

**Issue by Quizer9O8** [Ladysnake/Requiem#480]
I sometime notice when you're a possed mob for example a Zombie, if you're standing to close to another Zombie or hostile mob it will target you. Is this normal behavior since you're basically "one of them"? With Zombified Piglins there's the issue that Piglins try to target you if not wearing any gold armor, but are scared of you at the same time resulting in conflicting mob behavior.

**Comment by PsychoBreadstick** [comment]
Intended behavior, mobs can feel the presence of demons in the bodies of those they come in contact with, it can also be toggled with a gamerule.
