### ISSUE TITLE
Possessing others' shells causes bugs with Origins

### ISSUE THREAD

**Issue by Dual-Iron** [Ladysnake/Requiem#482]
I suspect this is a duplicate of #479, but I'm not sure; they didn't provide many details.

## To reproduce
1. Have two players, both demons, with different origins—let's say Player A has Origin A and Player B has Origin B.
2. Give both players Emancipation.
3. Have both players dissociate and swap bodies. They retain their original origins _and_ the other player's.
4. Have both players dissociate and swap bodies again.
5. Have both players disconnect and reconnect to the server.

## Effects
**Both players** will have the powers from **both origins**.

For instance:
- Player A's origin is Origin A. You can verify this with `/origin get @s origins:origin`
- Player A has the powers from Origin B and can't get rid of them (even in soul/mob forms!)
- If Player A changes their origin (e.g. Orb of Origin or `/origin set` command), only Origin A will be replaced
- All of this is true for Player B and their respective origins as well

[Here's a video example](https://streamable.com/m5lnbm). Ozql is an Enderian and MoonburnMC is a Feline.

This lets players accumulate more and more origins which breaks gameplay. As a server host, this means players aren't allowed to possess other players, which is rather sad.

**Comment by Pyrofab** [comment]
Thanks for the detailed report. I believe this issue is fixed in the latest beta.
