### ISSUE TITLE
Pandemonium Addon error 

### ISSUE THREAD

**Issue by arliegolden** [Ladysnake/Requiem#486]
![Screenshot 2022-01-30 at 21 26 09](https://user-images.githubusercontent.com/67831187/151718541-de62cfee-e7eb-4d51-a2f6-7bf88ee8cd3e.png)
 any idea why this is happening?

**Comment by Pyrofab** [comment]
Have you installed pandemonium on your client as well ?

**Comment by arliegolden** [comment]
I just did and it works but why can't I possess any mob?

**Comment by Pyrofab** [comment]
ah yeah you need to update the config as well

**Comment by arliegolden** [comment]
How do I do that?

**Comment by arliegolden** [comment]
?

**Comment by PsychoBreadstick** [comment]
No longer relevant
