### ISSUE TITLE
Sodium rendering bug

### ISSUE THREAD

**Issue by Dual-Iron** [Ladysnake/Requiem#488]
When [Sodium](https://github.com/CaffeineMC/sodium-fabric) (mc1.18.1-0.4.0-alpha6+build.14) is installed, runestones render as a missing texture.

![image](https://user-images.githubusercontent.com/31146412/153313525-830c9927-1fc1-4253-9e34-42640497257a.png)
![image](https://user-images.githubusercontent.com/31146412/153313544-802c304b-a213-4c28-9113-f8df78d7f34f.png)

**Comment by Eman-3600** [comment]
still not fixed lol

**Comment by ZestyBlaze** [comment]
Install Indium

**Comment by Pyrofab** [comment]
Yeah Requiem needs Indium if you install Sodium. This should now be specified in the mod metadata.
