### ISSUE TITLE
Mobs Don't Move Arms When Attacking

### ISSUE THREAD

**Issue by mario384** [Ladysnake/Requiem#49]
Simple problem, skeletons don't hold their arms up when shooting a bow or meleeing, and zombies don't move their arms when attacking either.

**Comment by Pyrofab** [comment]
(This behaviour normally comes from their AI, and would require special casing. As such I consider this an enhancement to the current behaviour rather than a bug)

**Comment by Pyrofab** [comment]
Actually fixed in Requiem
