### ISSUE TITLE
XP values are overwritten (not added to) when merging into a shell.

### ISSUE THREAD

**Issue by James103** [Ladysnake/Requiem#492]
As of Requiem 2.0.0 beta 7 and Minecraft 1.18.1, every player has their own XP values (same as in vanilla), but so does every player shell.

However, when a player soul merges back into a player shell, the soul's XP values are overwritten with the shell's XP values.
This can cause XP loss in case a player soul collects XP (through killing entities while possessing something and using the Humanity II enchantment), as whatever XP the soul just collected would be overwritten by the shell's XP.

This can be resolved by adding the soul's XP to the shell's XP when a player soul merges with a player shell.

**Comment by Pyrofab** [comment]
Should be fixed in beta 11.
