### ISSUE TITLE
[Question] Where to get empty soul vessels?

### ISSUE THREAD

**Issue by KamiSami** [Ladysnake/Requiem#497]
Title pretty much, despite server config being set as:

{
	"possession": {
		"allow_possessing_all_mobs": true
	}
}

Left or right clicking other mobs besides undead does not allow me to possess them.. Im surprised there was no reports oo this so far.. Unless there is new trick on possessing them? If so, how?

**Comment by KamiSami** [comment]
Well then, I just noticed there was new items... After testing some in creative I figured out how this works, changing title for now...

**Comment by KamiSami** [comment]
Something to add: Possession works on any entity now on a new day, no clue why, i did restart server yesterday but it didn't work at then... Now it does, again, no clue why this... Anyway im still curious where to get empty vessels in case i change the config again.

**Comment by Pyrofab** [comment]
I'd suggest you take a look at [our wiki](https://ladysnake.github.io/wiki/requiem/soul-vessels) for answers =)
