### ISSUE TITLE
Slight issue involving dissociating out of a player body

### ISSUE THREAD

**Issue by cloudythoughts06** [Ladysnake/Requiem#506]
Minecraft version: 1.16.5
Mod version: 1.7.14 (pandemonium also installed; same version)
Other mods installed: [see attached image]

Whenever I press the dissociate key to exit a player shell, it reloads all chunks and takes about a few seconds before gameplay resumes. Entering player shells & entering/exiting mobs are completely unaffected.

Gameplay is not affected majorly, but it tampers with the illusion a little.

![image](https://user-images.githubusercontent.com/77581443/160212113-1bcfbda4-2d63-4367-857d-ce2279cc3160.png)

**Comment by Eman-3600** [comment]
Is this still an issue as of the latest beta?

**Comment by cloudythoughts06** [comment]
I have not checked yet, but will provide updates when I do.

**Comment by Pyrofab** [comment]
This was indeed an issue with earlier versions, it should be approximately seamless now.
