### ISSUE TITLE
The player's movement speed unexpectedly becomes very large each time they join the server

### ISSUE THREAD

**Issue by Touch-Night** [Ladysnake/Requiem#512]
Fabric Server with requiem mod 2.0.0 beta7 and requiem pandemonium mod 2.0.0 beta7. 
The player's movement speed unexpectedly becomes very large each time they join the server.
If they died or changed the status between spirit and mobs(or player body), the speed effect will disapper.

**Comment by Touch-Night** [comment]
tips: this problem is different from #529

**Comment by Eman-3600** [comment]
Is this still an issue in Beta 9, what mods cause this, and what form(s) does the player have to be in?

**Comment by Touch-Night** [comment]
It has never happened in beta 9. At beta 7 time I only used requiem and pandemonium in my server. It happens specifically when player have a human body.
