### ISSUE TITLE
Unable to Cure Self on 1.18.1

### ISSUE THREAD

**Issue by empty-window** [Ladysnake/Requiem#513]
No matter what level of attrition, despite the gamerule, I am unable to cure myself with a weakness potion and golden apple. Being a zombie villager, or a regular zombie doesn't make a difference either.

**Comment by aaf19** [comment]
ok i had the same problem and i can tell you that it's a compatibilty issue with collective so sadly i couldn't play with mods like your items are safe

**Comment by empty-window** [comment]
Thanks for the insight.

**Comment by Fade-Alchemist** [comment]
If you are playing in 1.18.1 you can use Dark Rites 2 to use the cleansing ritual to cure yourself

**Comment by Pyrofab** [comment]
Thanks for the report ! It should finally be fixed in beta 11.
