### ISSUE TITLE
Player Speed Inexplicably Fast in Water

### ISSUE THREAD

**Issue by Omnivulf** [Ladysnake/Requiem#514]
Requiem version 2.0.0-beta.7, Pandemonium version 2.0.0-beta.7.

Tested primarily with skeletons and zombies, player speed is insanely fast when moving in water. May affect other mobs

Attatched Modpack export from Curseforge incase this is an issue with another mod interaction causing this =
[Modpack.zip](https://github.com/Ladysnake/Requiem/files/8566378/Modpack.zip)

**Comment by RedThunderG** [comment]
It won't help much but if it does come down to mods I have the same issue on my modpack so here's the modlist.html to overlay it
[Modlist](https://pastebin.com/3n160Jmp) 

> 

>

**Comment by KingMushroomBoy** [comment]
Oh its Origins.

**Comment by Pyrofab** [comment]
Thanks for the report, should be fixed in the latest beta.
