### ISSUE TITLE
compatibility issues with collective

### ISSUE THREAD

**Issue by aaf19** [Ladysnake/Requiem#515]
Hi i was doing a modpack(not public just to play with a friend) and installing it with collective makes you unable to cure i spend like a day seeing what was the thing failing and it was that mod (the problem is in the 1.18.1 beta)

**Comment by KingMushroomBoy** [comment]
Yeah and curing doesn't work either.

**Comment by Eman-3600** [comment]
Duplicates [this](https://github.com/Ladysnake/Requiem/issues/513)
