### ISSUE TITLE
problems playing with requiem and origins

### ISSUE THREAD

**Issue by aaf19** [Ladysnake/Requiem#516]
hi i'm the same guy that reported the compatibiity issues with collective and remember how i mentioned that it was to play with a friend? well after we make it all work i wanted to test the possesing another's player's body thing and it worked and it's cool that you get the origin of the other but also the abilites of both origins got mixed and after i got to my own body i still kept both origins abilities idk if it's a problem with origins or with requiem but if you can fix it then please do (the pic isn't on the server i did the image using the create shell thing since the bug can be done that way changing the origin and using /kill, then you go to the old body and you have both abilities as you can see with the double bar)
![image](https://user-images.githubusercontent.com/105087179/167330822-2ba62f24-6886-4ed4-8594-2e38ba45e5e1.png)

**Comment by Pyrofab** [comment]
I believe it should be fixed in the latest beta, please open a new issue if it still happens.
