### ISSUE TITLE
Compatibility issue with The bumblezone mod

### ISSUE THREAD

**Issue by Fade-Alchemist** [Ladysnake/Requiem#517]
The game will not load with the Bumblezone installed. They have been updated to allow for compatibility with this mod- per below 

[TelepathicGrunt](https://github.com/TelepathicGrunt) commented [on Feb 16](https://github.com/TelepathicGrunt/Bumblezone-Fabric/issues/47#issuecomment-1042376594)
@Sunconure11 Requiem hasn't been updated yet to use the new bumblezone hooks and codebase. You have to wait until their next update.

**Comment by KingMushroomBoy** [comment]
It says HASN'T, not has.

**Comment by Fade-Alchemist** [comment]
@KingMushroomBoy Exactly. Bumblezone has updated _their_  hooks and codebase to enable Requiem to be compatible once _Requiem_ updates. I know Requiem hasn't been updated, that is the point of this post. They should. (Before you chastise me for not reading a post correctly maybe make sure you read it right first.)

**Comment by KingMushroomBoy** [comment]
Alright, just trying to help. I didn't know they have updated their hooks.
