### ISSUE TITLE
Game crashes upon death.

### ISSUE THREAD

**Issue by madcaker** [Ladysnake/Requiem#518]
The game crashes upon dying as well as upon attempting to re-load the world.

My crash log is here: https://paste.ee/p/8AVCd
I'm currently debugging compatibility with other mods, notably iris sodium and indium.

**Comment by madcaker** [comment]
Update: Upon disabling shaders the world managed to load and I could choose between demon and human. I chose demon, but upon attempting to posses a nearby zombie the game crashed again and gave me this log. https://paste.ee/p/7Dw1p

**Comment by Pyrofab** [comment]
Well that's an incompatibility between Satin and Iris, you can either try removing Iris or picking different versions of both mods. I believe Satin 1.6.4 worked with the first few versions of Iris for 1.17 (or you could try updating to 1.18.1)

**Comment by Eman-3600** [comment]
I'm going to close this because it's a Satin problem rather than a Requiem problem.
