### ISSUE TITLE
Requiem doesnt work on 1.18.2

### ISSUE THREAD

**Issue by EEize** [Ladysnake/Requiem#520]
Here is the log https://pastebin.com/z8RwzPxf
My mods https://drive.google.com/file/d/1JARmZaCwDj-KDZHeUzzr6PuzyYc0M3Bz/view?usp=sharing

**Comment by James103** [comment]
Try removing any existing versions of Requiem (including `requiem 2.0.0-beta.7.jar`) from your instance then installing the new version of the mod from https://modrinth.com/mod/requiem/version/2.0.0-beta.8.

**Comment by ChaoticSeagull** [comment]
Same, Still doesn't work.
