### ISSUE TITLE
Possession Keep Inventory Doesn't Work on Humans

### ISSUE THREAD

**Issue by Eman-3600** [Ladysnake/Requiem#524]
Depossessing your human shell with the Possession Keep Inventory gamerule set to LIVING or ALWAYS leaves your gear with your player shell instead of letting you take it with.

**Comment by KingMushroomBoy** [comment]
Sorry but you are on of the unnoticed ones.  He probably wont reply anytime soon.

**Comment by Pyrofab** [comment]
Should be fixed now.
