### ISSUE TITLE
1.19 Ideas

### ISSUE THREAD

**Issue by Asteroid4** [Ladysnake/Requiem#527]
I have a bunch of ideas for this mod when it updates to 1.19.

1. You need an upgraded soul vessel to possess the warden. This it because it has many souls in its chest, and those need to be removed to possess it.
2. If you are not in player form, you shouldn't trigger sculk shriekers unless you are touching the sculk. Sculk sensors don't set off shriekers unless players are on the sculk, but if you touch the sculk, it can tell you are really a player, like any other mobs.
3. Using a soul vessel on sculk causes it to lose charge somehow. Idk about this one, but imagine making exp bottles from sculk somehow!
4. That's all the ideas for now, thx for reading!

**Comment by Asteroid4** [comment]
Or maybe for idea 1, you need to use many soul vessels, each weakens the warden some more untill you can possess it.

**Comment by Eman-3600** [comment]
Post ideas in the Ladysnake discord in the suggestions channel. Also the warden should not be possessable because it's basically a boss mob (like the ender dragon and wither) with 500 hp that hits like a truck.

**Comment by Asteroid4** [comment]
Ok, I'll repost this there.

**Comment by Asteroid4** [comment]
Where is the discord?

**Comment by Eman-3600** [comment]
https://discord.gg/Gz2ruqjm

**Comment by Eman-3600** [comment]
https://discord.gg/Gz2ruqjm

**Comment by Asteroid4** [comment]
Thanks!
