### ISSUE TITLE
Movement become very fast when Origins installed

### ISSUE THREAD

**Issue by Touch-Night** [Ladysnake/Requiem#529]
server mods list:
fabric-api-0.56.1+1.18.2
Origins-1.18.2-1.4.1
requiem-2.0.0-beta.8
requiem-pandemonium-2.0.0-beta.8

If possess a mob that isn't in water, movement speed become extremely fast in water. Also, if possess a mob that is originally in water, the problem disappear.

**Comment by Asteroid4** [comment]
What if you use the human origin? it should have no effect.

**Comment by Eman-3600** [comment]
The glitch is present no matter your origin.

**Comment by USMP-lancer** [comment]
issue still present on beta 9, its very funny, but also kinda game breaking

**Comment by Pyrofab** [comment]
Thanks for the report, should be fixed in the latest beta.

**Comment by Pyrofab** [comment]
Duplicate of #514 by the way
