### ISSUE TITLE
Mod not functioning on hardcore (1.18.2)

### ISSUE THREAD

**Issue by Venomleopard120** [Ladysnake/Requiem#533]
I had been playing on a new hardcore server, had a base and was preparing for the nether. Welp, I got unlucky and accidentally walked right into a creeper and died. And then? Death screen! This was odd, considering I used origins and had selected demon as my soul type, and the mod worked on normal worlds. But, for some reason, I just ended up in spectator mode in my hardcore world. So, I removed all mods except Requiem, fabric api, sodium, and a few other optimization mods and made a new hardcore world. I quickly threw myself off a cliff and was sent to the main menu. Didn't ask me to pick my soul type or anything, now that I didn't have origins. Am I dumb or is it bugging out?
full list of mods:
requiem 2.0.0 beta 
fabric api
lithium-fabric
modmenu
Pehkui
phosphor-fabric
sodium-fabric
indium

**Comment by Venomleopard120** [comment]
Oh, this was also said elsewhere but yeah, possessing stuff with origins gets a bit funky with water.

**Comment by Pyrofab** [comment]
Working as intended, the 2.0 update makes hardcore a breeze if we let you respawn on death. You can still become a ghost through [emancipation](https://ladysnake.github.io/wiki/requiem/effects#emancipation).
