### ISSUE TITLE
Cured creatures seem to have a soul

### ISSUE THREAD

**Issue by DarianLStephens** [Ladysnake/Requiem#534]
After curing a piglin, or villager, while possessing its body, the resulting creature seems to have a soul.
It will move on its own when de-possessed, and its soul can be removed with a Soul Vessel.

**Comment by Pyrofab** [comment]
That's actually a feature ! Villagers lose their soul when they get zombified and regain it when they get cured.

**Comment by DarianLStephens** [comment]
What about those that spawned as a zombie, or piglins?
It just seems weird that they're able to run around on their own, and be re-possessed while they still have their own soul.
It also raises the issue of why regular cured Zombies don't keep a soul, unless they've been a zombie too long or something?

**Comment by Pyrofab** [comment]
In our lore, the villager/piglin soul is suppressed while zombified, and by curing the mob while possessing it you force the lesser soul to accept you. Regular zombies do not have an equivalent cured mob, so they are considered to be a blank slate that you can shape into a player body.
