### ISSUE TITLE
The Choice GUI appears even after using commands to set your state to remnant.

### ISSUE THREAD

**Issue by Eman-3600** [Ladysnake/Requiem#536]
If you use the command:
  /requiem remnant set requiem:remnant
it'll set your state to remnant. However if your next death is your first, you will be greeted with the Choice GUI despite having already set your remnant/soul type.

Potential Fix: Add a new default soul type (does not refer to origins soul type but rather the internal one): unchosen. It functions as mortal but dying will cause the choice dialogue to show (unless in hardcore). This will make any changes to the player's soul type lock it in automatically while additionally allowing commands to undo the choice, reenabling the dialogue on the next death.

**Comment by Touch-Night** [comment]
and it may fix the bug that players' soul type are set to remnant in default even though I set the startingremnanttype gamerule to CHOSEN

**Comment by Pyrofab** [comment]
I wouldn't say it's a bug, if you want to prevent the menu from appearing you can give the choice advancement.

**Comment by Eman-3600** [comment]
ohhhh yeahhhh I forgot it's linked to the advancement

**Comment by Pyrofab** [comment]
Well, closing this since I believe it should be fine to deal with the advancement separately.

**Comment by Eman-3600** [comment]
fine by me
