### ISSUE TITLE
Selected Slot Desync

### ISSUE THREAD

**Issue by Eman-3600** [Ladysnake/Requiem#539]
If you possess a player shell that has a hotbar slot selected other than the first one, your client will appear to select the first slot. The server will still think you've selected the slot that the shell had selected (which would be the correct one).

https://user-images.githubusercontent.com/98138568/179375348-dce2a6f3-cca2-44a2-a97a-9d7bef6bfac9.mp4

**Comment by Eman-3600** [comment]
You can tell this is a client-server desync because game interactions treat you as if you're holding the correct item, such as here:

https://user-images.githubusercontent.com/98138568/179375409-55cc1aa0-e2bf-4cbe-9d8f-a8852f057b45.mp4

This clip was taken after the setup I showed in the initial comment. I hold right click, and the server has me eat my steak. Upon depossessing the shell it shows I was holding the steak the entire time.

**Comment by Touch-Night** [comment]
This problem happens not only on player shell, but also on mobs.
Sometimes, if you possess a armed skeleton, and take off the armor, it become unarmed client side. But if you dissociate, it become armed again. Possess again, unarmed.
