### ISSUE TITLE
No Class Definition for Baritone ServerFakePlayerFactory on Quilt

### ISSUE THREAD

**Issue by Infinidoge** [Ladysnake/Requiem#540]
Attempting to launch Requiem fails, with it stating that it is missing the ServerFakePlayerFactory from the Baritone API.

Minecraft version: 1.19
Quilt loader version: 0.17.0
QSL/QFAPI version: 2.0.0-beta.7 & 0.57.0
Requiem version: 2.0.0-beta.10

Full log: https://mclo.gs/qwlVGZB

I assume that the Requiem jar build failed to `JIJ` the Automatone API, leading it to be missing.

**Comment by Eman-3600** [comment]
Yeah I'd say this is a pretty urgent issue.

**Comment by Pyrofab** [comment]
Oh, yeah that's a funky issue because mod resolution changed. Anyway, it's fixed in beta 11.
