### ISSUE TITLE
Villager changes its profession after dissociation

### ISSUE THREAD

**Issue by Touch-Night** [Ladysnake/Requiem#543]
I possessed a cleric zombie villager and cured myself and became a cleric, but after dissociation it became a leatherworker
![image](https://user-images.githubusercontent.com/102669562/179875814-f43e78ca-4c71-4ad8-8411-b583f9fc8e0d.png)

**Comment by Eman-3600** [comment]
fairly sure this is a nonissue but we'll see what Pyrofab thinks
