### ISSUE TITLE
Trinket Slot Coincidences

### ISSUE THREAD

**Issue by Eman-3600** [Ladysnake/Requiem#544]
For some reason, if you die in Requiem, your first hotbar slot and the ring slot from Trinkets API become linked until you relog.
![Slot Mirroring](https://user-images.githubusercontent.com/98138568/179878061-e636fd12-6f32-4854-a1eb-118b2bb7651a.png)

**Comment by Eman-3600** [comment]
I have yet to test what this does to different slots when the ring slot is disabled (switching the enabled slots is a pain). I can only assume this has to do with slot IDs coinciding.

**Comment by Touch-Night** [comment]
Sometimes hat slot

**Comment by Pyrofab** [comment]
Alright, found the issue after a couple of hours of headscratching. Requiem adds a dedicated mainhand slot, for smaller mob inventories (eg foxes). Under normal circumstances (depending on mod loading order), this slot is added after Trinkets'. However, when you die, Trinkets refreshes its slots *clientside*, removing all the existing ones and adding them back while disregarding that requiem's mainhand slot exists. So on the client, the latter slot is before the former while on the server it's the opposite. So when you try to interact with the first Trinkets slot, the server thinks you are actually interacting with Requiem's mainhand slot, and mayhem ensues.

I got a quick fix, but something more permanent should probably be done Trinkets-side, as I am pretty sure Requiem won't be the only mod triggering this bug.

**Comment by netcore10** [comment]
i think this issue still persists on beta 15

**Comment by Touch-Night** [comment]
Yes.
