### ISSUE TITLE
Crosshair Shader appears when it shouldn't

### ISSUE THREAD

**Issue by Eman-3600** [Ladysnake/Requiem#545]
The shader meant to apply on the crosshair when you are about to try to possess an enderman in the end with a soul (which would return you to the Overworld) is also applied when alive.
![Broken Crosshair](https://user-images.githubusercontent.com/98138568/179890654-3eea467b-272a-48be-9f5c-1a1f0e9c6666.png)

**Comment by Pyrofab** [comment]
Oops (fixed)
