### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by KeeveeKoomoo** [Ladysnake/Requiem#554]
Game version: 1.19.1
Mod version: 2.0.0 beta 12
Enabled Mods: Quilted Fabric API, Requiem
Quilt Loader version: 0.17.2 beta 2 1.19.1
Quilt API version: "qfapi-4.0.0-beta.1_qsl-3.0.0-beta.2_fapi-0.58.5_mc-1.19.1"
Issue:
When I press play with the quilt launcher my game doesn't open, the launcher closes, opens again with "exit code 1".
Game works fine without requiem.
Tried solutions:
Reinstalled requiem, Reinstalled quit loader, Reinstalled quilt api, Dedicated more ram to minecraft (8GB)

**Comment by Pyrofab** [comment]
Can I see the crash report file from your minecraft instance directory ?

**Comment by netcore10** [comment]
i got the same issue, here's a log https://mclo.gs/EROJdPQ

**Comment by netcore10** [comment]
a notable part is impersonate.

**Comment by Pyrofab** [comment]
Ah yes, incompatibility with minecraft 1.19.1. Could you try with [the latest impersonate version](https://www.curseforge.com/minecraft/mc-mods/impersonate) ?

**Comment by netcore10** [comment]
that worked! it launched. I suppose because other modloaders don't download requirements it's hard to keep up with what they need along side.  (Quilt isn't on curseforge yet.)

**Comment by netcore10** [comment]
Now i get an error when i try to load a world of ''invalid player data'' any reason that might be? 

https://mclo.gs/YFcCl6H

**Comment by Eman-3600** [comment]
Best guess would be Cardinal Components not working properly in 1.19.1, I'll be checking that out right now.

**Comment by Eman-3600** [comment]
After some testing Cardinal Components seems to be fine, at least the latest version, not bundled within Requiem

**Comment by Pyrofab** [comment]
Yeah it's automatone. I'm updating it next.

**Comment by Eman-3600** [comment]
ah yeah

**Comment by Pyrofab** [comment]
Fixed in beta 13
