### ISSUE TITLE
QSL/QFAPI BETA 7 Client and server Crash on 1.19.1

### ISSUE THREAD

**Issue by netcore10** [Ladysnake/Requiem#564]
client
https://paste.atlauncher.com/view/3f41fea5-2f67-4068-8886-6aeb0d309983

Server
https://mclo.gs/KtnxQtG

**Comment by Touch-Night** [comment]
Incompatible with origin?
Could not get origin from id 'requiem:vagrant', as it was not registered!

**Comment by netcore10** [comment]
It works on beta 5

**Comment by netcore10** [comment]
nvm they updated

**Comment by netcore10** [comment]
it still crashes on a server
