### ISSUE TITLE
[Bug] Possessing another player's shell permanently changes your origin to theirs

### ISSUE THREAD

**Issue by Dual-Iron** [Ladysnake/Requiem#565]
The following applies when Origins 1.6.2 and Requiem 2.0.0-beta.12 are installed on Minecraft 1.19.

## Bug
After possessing a player shell, your origin permanently changes to that of the possessed shell's. You can test this by dying and using `/requiem vagrant set false`, or by possessing a zombie and curing yourself.

## Expected behavior
After leaving a player shell through death or dissociation, your origin should reset to what it was before entering that player shell.

**Comment by nullAdept** [comment]
this doesn't happen in 1.18.2

**Comment by Dual-Iron** [comment]
Fixed in Beta 15! 💙
