### ISSUE TITLE
Crystal heart from the artifacts mod doesn't give additional health

### ISSUE THREAD

**Issue by nullAdept** [Ladysnake/Requiem#568]
### Mods&versions
https://www.curseforge.com/minecraft/mc-mods/artifacts 1.18
Requiem 2.0.0 beta 9 
### Compatibility issue
it doesn't :(

**Comment by Pyrofab** [comment]
Alright it was easy enough to find, but for next time could you please link to the conflicting mod and note the versions (Minecraft, Requiem, conflicting mod) that you used ?

**Comment by nullAdept** [comment]
will do, will fix

**Comment by PsychoBreadstick** [comment]
Duplicate of https://github.com/Ladysnake/Requiem/issues/326
