### ISSUE TITLE
Incompatibility with Origins

### ISSUE THREAD

**Issue by MLMII** [Ladysnake/Requiem#571]
Requiem 2.0.0-beta.13
Origins 1.19-1.6.2

Crashes at world creation, if I read the crash log correctly the "vagrant" origin isn't registered.  

The issue also exists with pandemonium installed.

Thank you for your time

[crash-2022-08-21_18.21.44-client.txt](https://github.com/Ladysnake/Requiem/files/9390329/crash-2022-08-21_18.21.44-client.txt)

**Comment by Dual-Iron** [comment]
Origins doesn't work correctly on 1.19.1 or 1.19.2

**Comment by KingMushroomBoy** [comment]
Yeah this happens to me too!
