### ISSUE TITLE
Better Combat mod incompatibility

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [Ladysnake/Requiem#575]
Hello!

Both mods are targeting the same LivingEntityRenderer.features field, causing a Mixin exception.
Related issue: https://github.com/ZsoltMolnarrr/BetterCombat/issues/83

Unfortunately I don't know a technical solution for this. Do you have an idea?

Better Combat:
https://github.com/ZsoltMolnarrr/BetterCombat/blob/1.19.X/common/src/main/java/net/bettercombat/mixin/client/firstpersonrender/LivingEntityRendererMixin.java

The Requiem:
https://github.com/Ladysnake/Requiem/blob/1.19/src/main/java/ladysnake/requiem/mixin/client/remnant/LivingEntityRendererMixin.java

**Comment by PsychoBreadstick** [comment]
Both mods from my testing in the current latest version of both mods seemingly works fine. Likely fixed in some recent update.

**Comment by PsychoBreadstick** [comment]
Nvm, there are a few first-person rendering issues when using swords while possessing a non-player shell.

**Comment by Redfan2** [comment]
This issue will be closed as there is no solution without compromising on functionality in Requiem
