### ISSUE TITLE
Quick update to 1.19.2

### ISSUE THREAD

**Issue by BrymalHS** [Ladysnake/Requiem#578]
I've tried using the newest beta release made for 1.19.1 hoping it works with the latest version, unfortunately it does not as one could have probably assumed. Just wishful thinking... Will you please update this wonderful masterpiece of a mod to 1.19.2? I am waiting on starting my HCSP world for this specific mod as that is how important and lovely it is :)

**Comment by Pyrofab** [comment]
Could you maybe try adding the latest version of [impersonate](https://curseforge.com/minecraft/mc-mods/impersonate) to your mods alongside requiem ? I'm not sure but it may fix your issue.
