### ISSUE TITLE
Vanillafix - Voidcraft - and Erebus bone block issue

### ISSUE THREAD

**Issue by Caopr** [Ladysnake/Requiem#58]
As a ghost its possible to be killed by a cactus thus turning into a SUPER GHOST. also bumping into the block left behind by a player death with erebus as a ghost crashes the game. Have a crash report
[crash-2018-08-15_16.23.28-client.txt](https://gist.github.com/Pyrofab/1860d094a4688c3fba877f01e70173f1)

**Comment by Caopr** [comment]
Also drowning as a ghost

**Comment by Pyrofab** [comment]
I don't take damage from cacti as a ghost, in fact you should phase right through them.

**Comment by Pyrofab** [comment]
I don't appear to drown either. I think you have another mod interfering.

**Comment by Caopr** [comment]
Weird :o just tested again. am able to phase through cacti but get hurt along the way. alright I don't know what mod would cause it but thanks anyhow

**Comment by Pyrofab** [comment]
And this crash report *really* makes me want to blame it on a coremod. The stackstrace doesn't match anything I have.

**Comment by Caopr** [comment]
Probobly some weird physics thing then. I didint know erebus had its own gravestone thing. sorry for the trouble

**Comment by Pyrofab** [comment]
No problem. Please report back if you find the culprit, maybe I could work with that.

**Comment by Caopr** [comment]
Not sure if its a priority or if its just another thing only for me . but dying as a possessed mob with a gravestone mod active doesent make a gravestone on death.. dying as a ghost did if that helps any.
