### ISSUE TITLE
More player nbt tags

### ISSUE THREAD

**Issue by Dunk0w0** [Ladysnake/Requiem#581]
This is a request not an issue but it would be extremely useful for doing stuff with commands if there were more custom nbt tags. One that would be particularly useful for me is a tag that tells whether or not a player still has their shell alive if they disassociated. But others would be nice too, such as what entity they are possessing and stuff like that.

**Comment by Pyrofab** [comment]
I don't really like adding extraneous NBT - would mod-provided [predicates](https://minecraft.fandom.com/wiki/Predicate) work for you ?

**Comment by Dunk0w0** [comment]
Yeah predicates would work! I was just thinking of any way to select certain players/entities using commands so I suggested nbt tags but whatever works for you is good!

**Comment by Pyrofab** [comment]
New predicates are now available in beta 15, more information is available [on the wiki](https://ladysnake.github.io/wiki/requiem/commands#predicates)

**Comment by Dunk0w0** [comment]
That was so quick! Thank you so much!

**Comment by Pyrofab** [comment]
Oh almost forgot - feel free to drop by our discord to share your datapack if that's what you are doing, we always enjoy seeing what our community is coming up with 😃

**Comment by Dunk0w0** [comment]
Will do! I'm actually doing a modded SMP that revolves around Requiem but with a couple modifications here and there!
