### ISSUE TITLE
Zombie will attack itself after dissociation.

### ISSUE THREAD

**Issue by Touch-Night** [Ladysnake/Requiem#593]
Zombie will attack itself after dissociation if you use its body to attack other zombies during possession. It' weird.

**Comment by Dunk0w0** [comment]
i have noticed this too, it looked like it was getting attacked by something invisible because it had knockback but it attacking itself makes sense

**Comment by Touch-Night** [comment]
Zombie will never attack itself in vanilla game. Not if you make a zombie hate another one somehow.

**Comment by Eman-3600** [comment]
Have you tried it with other hostile mobs?

**Comment by Touch-Night** [comment]
> Have you tried it with other hostile mobs?

Yes, it's not happen on skeleton and enderman. It seems that this issue only happen on zombie and zombie village.

**Comment by ruan128** [comment]
it also happens with other zombies variants like husks if you attack another husk

**Comment by PsychoBreadstick** [comment]
Seemingly fixed in a recent update.

**Comment by Pyrofab** [comment]
Also duplicate of #476, and fixed for real in the upcoming MC 1.19.3 version
