### ISSUE TITLE
While possessing a mob you attack a hostile mob every mob nearby becomes hostile to you, including different types of mobs

### ISSUE THREAD

**Issue by kristibektashi** [Ladysnake/Requiem#596]
For example if you attack a zombie and there is a skeleton nearby the skeleton will attack you too. This also happens if the other mob attacked you first, and this even happens if you are possessing the same type of mob.

This only happens if /gamerule requiem:possessionDetection is set to NORMAL or HARD

**Comment by ShadeTDW** [comment]
I think that's purposeful.

**Comment by kristibektashi** [comment]
> I think that's purposeful.

But it makes no sense since they don't do it in vanilla. For example if a skeleton shoots a zombie only the zombie attacks it, nearby mobs will not attack it

**Comment by Pyrofab** [comment]
We found the game boring when nothing ever attacked you so we changed it.
The [gamerule](https://ladysnake.org/wiki/requiem/configuration#requiem-possessiondetection) is explicitly here for you to revert that change if you want to.

**Comment by kristibektashi** [comment]
> We found the game boring when nothing ever attacked you so we changed it. The [gamerule](https://ladysnake.org/wiki/requiem/configuration#requiem-possessiondetection) is explicitly here for you to revert that change if you want to.

Ok but why does it happen even when the other mob attacked first?

**Comment by kristibektashi** [comment]
> We found the game boring when nothing ever attacked you so we changed it. The [gamerule](https://ladysnake.org/wiki/requiem/configuration#requiem-possessiondetection) is explicitly here for you to revert that change if you want to.


Also what about mobs that naturally attack each other, such as piglins and wither skeletons? I don't this this should happen in that case (e.g. when you attack a piglin as a possessed wither skeletons other wither skeletons around you shouldn't turn on you since these mobs attack each other in vanilla)
