### ISSUE TITLE
1.19.2 crash with latest quilt fabric API (I think)

### ISSUE THREAD

**Issue by netcore10** [Ladysnake/Requiem#598]
https://paste.atlauncher.com/view/a63d699b-5edc-4022-9ea3-40017edb7dbb

**Comment by kristibektashi** [comment]
Downgrading to older version of Quilted Fabric API works, but some other mods require the newer version which might become an issue

**Comment by netcore10** [comment]
> Downgrading to older version of Quilted Fabric API works, but some other mods require the newer version which might become an issue

Exactly my worry.

**Comment by kristibektashi** [comment]
@Pyrofab anything to say about this?

**Comment by netcore10** [comment]
https://github.com/QuiltMC/quilt-standard-libraries/issues/224#issuecomment-1334065797

**Comment by PsychoBreadstick** [comment]
After using the latest QSI I have gotten no crashes as a result. Is this still occurring for you with the latest versions of the mods mentioned?

**Comment by netcore10** [comment]
Oops! Forgot this was still here, seems to work fine last i tested
