### ISSUE TITLE
error emancipating on server side only

### ISSUE THREAD

**Issue by netcore10** [Ladysnake/Requiem#603]
https://mclo.gs/gMnsEbs

**Comment by PsychoBreadstick** [comment]
Is this still effecting you on beta 16?

**Comment by netcore10** [comment]
i havent been able to test, due to our community shifting our goals, but it atleast fixed the launch error

**Comment by Redfan2** [comment]
Hi, does this issue still exist? If yes, could you please explain a bit clearer how you encountered this issue? I have no idea how to reproduce it based on the log and the issue title

**Comment by netcore10** [comment]
I've lost the ability to test, so i'm closing this because i can't really help.
