### ISSUE TITLE
Can't deal melee damage to Ender Dragon as undead

### ISSUE THREAD

**Issue by emeryplyler** [Ladysnake/Requiem#621]
For some reason, I can't hit or deal damage to the dragon when not in my human body. I don't know if this is intentional or if anyone else has ever had this problem. It may be an issue on my side. I'm playing 1.18.2, Requiem version 2.0.0 beta 9.

**Comment by Pyrofab** [comment]
Yeah regular mobs cannot damage the enderdragon AFAIK - humanity-enchanted weapons should work though

**Comment by emeryplyler** [comment]
Ohh I see. Thank you!
