### ISSUE TITLE
Possession causes super speed when in contact with water

### ISSUE THREAD

**Issue by Creeper2006** [Ladysnake/Requiem#630]
Precisely what it says on the label. For some reason, possessing an undead mob makes you go superfast in water.
I apologise for the extremely poor footage, I had to compress it to 480p in order to fit it here, and my computer struggles running the game by itself, let alone recording it as well.

https://github.com/Ladysnake/Requiem/assets/64898415/ee3b972e-aed5-4240-ba32-efecc65af779
https://github.com/Ladysnake/Requiem/assets/64898415/9ee48476-4455-4bb0-b67f-eccef7db2cc3

I believe that this may be a mod incompatibility, so a list of all the mods installed in this instance can be found here.

![image](https://github.com/Ladysnake/Requiem/assets/64898415/713ee1e6-b29f-43a6-b483-e86efb0ed761)
![image](https://github.com/Ladysnake/Requiem/assets/64898415/79fe043e-e413-4b7b-b055-537d783f6a6d)
![image](https://github.com/Ladysnake/Requiem/assets/64898415/c4505449-8703-4e90-a592-1a8c98c9cd55)

**Comment by Creeper2006** [comment]
Alright. I did some Mod PoE and narrowed most of the problem down to a single suspect.
https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric/files/4428185

However, I noted the problem still occurred when a possessed zombie turns into a drowned, even without YUNG's API.

**Comment by Creeper2006** [comment]
Disregard the previous message.
The true culprit was Origins.
Apparently Origins isn't compatible with Requiem, despite Pandemonium having a feature which adds an origin to the list.

Should I close this post?

**Comment by Pyrofab** [comment]
Oh, sorry for not answering earlier, but this issue has been fixed since the Requiem update for MC 1.19, or maybe earlier (would need to check the changelog).

**Comment by Creeper2006** [comment]
Oh, ok. Looks like I'll have to move up yet again.
