### ISSUE TITLE
Config Pandemonium 1.18.2: How to change a rule in config?

### ISSUE THREAD

**Issue by A1Enigma** [Ladysnake/Requiem#645]
The mod page says "- Adds a config option to be able to possess any mob without capturing their soul first," for 2.0.0 or above, however I can't find that in the config page, only the allow all mobs possession setting. How do I change this setting?

**Comment by Pyrofab** [comment]
Yep, that's the option you are looking for. Just set it to "true" and you will be able to possess any mob as if they were zombies.

**Comment by A1Enigma** [comment]
Does this require a world reset to work? I changed it to true but it didn't do anything (aternos server).

**Comment by A1Enigma** [comment]
does this look right?
![Screenshot 2023-11-19 201527](https://github.com/Ladysnake/Requiem/assets/82793696/717cadfe-fb38-4be8-b7f3-8c768031c26c)

**Comment by Pyrofab** [comment]
That option needs to be set on both client and server, then you need to restart both (but no world reset required)
