### ISSUE TITLE
Update to 1.20.1/2?

### ISSUE THREAD

**Issue by ComradeCaro** [Ladysnake/Requiem#648]
The mod seems dead at this point which is really sad considering how great it is. Really hope you decide to update it if you find the time to do it. If you don't want to update the mod please consider marking the mod as discontinued for future users wanting to use the mod. Thank you for your time :heart:

**Comment by Redfan2** [comment]
This mod is not dead, in fact a port is in the works, it's just that there were 11 libraries that needed to be ported plus the mod itself.

**Comment by kimjongbing** [comment]
> This mod is not dead, in fact a port is in the works, it's just that there were 11 libraries that needed to be ported plus the mod itself.

is there an ETA on this?

**Comment by Redfan2** [comment]
> > This mod is not dead, in fact a port is in the works, it's just that there were 11 libraries that needed to be ported plus the mod itself.
> 
> is there an ETA on this?

Only @Pyrofab knows that.

**Comment by Pyrofab** [comment]
Refer to #654 for the latest status update.

**Comment by kristibektashi** [comment]
For anyone watching this issue, read [this comment](https://github.com/Ladysnake/Requiem/issues/633#issuecomment-3225381338) for more info on the 1.20 port
