### ISSUE TITLE
On death, nothing happens

### ISSUE THREAD

**Issue by EmpressAbrella** [Ladysnake/Requiem#649]
on death, the effect takes place, turning me incorporeal, putting a white light at my center and turning the world grey but instead of what I read was supposed to happen (the whole thing where you choose to become a demon) instead I am just left there fully able to move around, with half a heart, my full inventory, and an inability to interact with the world around me or take damage. The only way to end this is to type /kill and hit respawn. 

I'm fully aware this is likely due to another mod, but as I'm still unsure which mod I figured I'd post this here in case someone else runs across this issue and needs to know what mods might be causing this issue in particular. Will update when I've solved the conflict so that the mod in question can either be avoided or a patch for it can be made (depending on how popular the mod is and how much it conflic).

**Comment by Redfan2** [comment]
Do you have Rat's Mischief installed? The Requiem Lite it bundles always causes this issue

**Comment by EmpressAbrella** [comment]
it is in fact an issue with Rat's Mischief (thank you for that @Redfan2 )
