### ISSUE TITLE
How to get your items back?

### ISSUE THREAD

**Issue by GuiTaek** [Ladysnake/Requiem#651]
This is a question. When you die in the sun light, how are you supposed to get your items back when you don't have keep inventory? I have found no theoretical solution to this, I'm sorry if the question is silly. I didn't found anything on the internet and pondering didn't help either.

**Comment by Pyrofab** [comment]
You have a few options :
- bruteforcing
  - rushing (assuming you are close enough to a cave entrance)
  - digging a tunnel in the dirt to your items
  - sacrificing a few bodies to refresh the item despawn time until the night
  - unloading the chunk until the night
- finding a way to resist the sunlight
  - finding a helmet
  - finding a husk
  - converting a zombie into a husk
  - getting into the nether and finding a zombie piglin

I'm sure there are other ways people found, but that's at least what I can think of

**Comment by GuiTaek** [comment]
Thanks for the fast answer, here is my answer:

> You have a few options :
> 
> * bruteforcing
>   
>   * rushing (assuming you are close enough to a cave entrance)
Yeah, sometimes it could work
>   * digging a tunnel in the dirt to your items
That also assumes that you are near a cave, but yeah it could work
>   * sacrificing a few bodies to refresh the item despawn time until the night
Sounds difficult
>   * unloading the chunk until the night
That sounds doable nearly always.
> * finding a way to resist the sunlight
>   
>   * finding a helmet
In a cave without wood nearly impossible
>   * finding a husk
Yeah, in a base or a desert possible
>   * converting a zombie into a husk
I tried suffocating a zombie into a husk, this doesn't work. Is there a vanilla feature I don't know about?
>   * getting into the nether and finding a zombie piglin
Again, only possible in a base

I think I'll stick to keepInventory, but thanks for the incredible fast answer and happy holiday 🙂.

**Comment by Pyrofab** [comment]
No problem, happy holidays as well 👍
