### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by raywilsondesign** [Ladysnake/Requiem#654]
Hey! I am really interested in this mod and would love to add it to my modded server, could it be updated to 1.20.1?

**Comment by Pyrofab** [comment]
Hi, it's coming eventually, but I really just started the port after a full year of barely keeping all our other mods and libraries up to date - so I wouldn't count on it too soon if I were you.

**Comment by ServiceGames** [comment]
@Pyrofab is there an update on this?

**Comment by kristibektashi** [comment]
> [@Pyrofab](https://github.com/Pyrofab) is there an update on this?

Read [this comment](https://github.com/Ladysnake/Requiem/issues/633#issuecomment-3225381338) for more info on the 1.20 port
