### ISSUE TITLE
[question] using part of your mod

### ISSUE THREAD

**Issue by GuiTaek** [Ladysnake/Requiem#656]
``Hello again! I just want to say, I appreciate your Rift Screen and I'd like to use (and modify in my repo) the RiftScreen class. Unfortunately, our both licenses are incompatible, I will have MIT, and I'd rather use another teleportation screen than changing my license. The mod is not public yet but will be, including the source eventually. I understand this part of your license:
`
Note that people who make modified versions of this mod are not obligated to grant
 * this special exception for their modified versions; it is their choice whether to do so.
 * The GNU General Public License gives permission to release a modified version without this exception;
 * this exception also makes it possible to release a modified version which carries forward this exception.
`

As it being no problem, but I thought, I ask you just in case. I'll credit you in the file and wherever and however you want.

**Comment by Redfan2** [comment]
This is a question for @Pyrofab

**Comment by GuiTaek** [comment]
OK, thanks for the fast answer!

**Comment by Pyrofab** [comment]
Yep, it is indeed a question for me. I'm afraid your reading of the license is slightly off the mark - the exception in question is specifically "linking to minecraft and LGPL code", which means MIT code is not covered. However, I can give you permission to use that code in your work, provided your code is indeed open source, that you keep the license header on the file, and that you link back to this repository (and I would advise also linking to this issue to show you got permission).

**Comment by GuiTaek** [comment]
Thanks a lot, that's very kind of you!!! I will do as requested, and I will publish my code immediately after pushing this file. And I will link the repo here for convenience. Yeah, for the static linking, I had this thought, too, but I didn't understood the exception in question. Thanks a lot again, I really like your code and would be sad, if I had to use another repo. I will close the issue as soon as I linked the repo back, and did the requested things, it shouldn't be a problem, should it? And also thanks for the again fast answer!

**Comment by GuiTaek** [comment]
I just thought about not publishing immediately, and I noticed, that there is no reason to not immediately publish the repo as requested. The file is not yet present, as I waited before even commiting to the result of this discussion.
here the link:
[techno-enderling](https://github.com/GuiTaek/techno-enderling)

**Comment by GuiTaek** [comment]
And finally the [commit](https://github.com/GuiTaek/techno-enderling/commit/433cd796f78edc118a6610509bce2f8927c2884c) that introduced the [file](https://github.com/GuiTaek/techno-enderling/blob/433cd796f78edc118a6610509bce2f8927c2884c/src/main/java/com/gmail/guitaekm/technoenderling/gui/TeleportScreen.java) in question. Closing now.
