### ISSUE TITLE
Suggestion：The effect such as weakness can improve the percent when you remove the mob soul

### ISSUE THREAD

**Issue by adsa547** [Ladysnake/Requiem#660]

**Comment by Redfan2** [comment]
Hey, could you please give a clearer explanation of what you suggest and why you think it will be beneficial to the Mod?

**Comment by Xiribidus** [comment]
I'm pretty sure they mean that a mob that has weakness should be easier to unsoul, which should be the case for anything with attack damage already as soul capture chance partially depends on attack damage

**Comment by adsa547** [comment]
i mean the “Potion with weakness”

**Comment by adsa547** [comment]
Mob with a weakness buff have an increased chance of removing the mob‘s soul

**Comment by adsa547** [comment]
> I'm pretty sure they mean that a mob that has weakness should be easier to unsoul, which should be the case for anything with attack damage already as soul capture chance partially depends on attack damage

that's what i want to express
