### ISSUE TITLE
Infinite Resource Pack reload. [REQUIEM LITE AND REQUIEM]

### ISSUE THREAD

**Issue by lumithespoofy64** [Ladysnake/Requiem#668]
[ENTIRE LOG]
https://mclo.gs/liR8QO4

[Problem]
**The resource pack infinitely reloads. Both Requiem LITE and Regular Requiem.**

:( i just wanna use rats mischief

**Comment by Xiribidus** [comment]
Rats Mischief loads a core version of Requiem, making the two incompatible with the current latest versions

**Comment by Syclusion** [comment]
> Rats Mischief loads a core version of Requiem, making the two incompatible with the current latest versions

It isn't rats mischief, the problem is create. Just tested until i found the problem myself, I beleive satin (and therefor requiem) completely craps itself when the newest create version is installed.

**Comment by Syclusion** [comment]
Hmm wait, nope seems its requiem. Loaded with satin and no crash, just with requiem.

**Comment by lumithespoofy64** [comment]
> Hmm wait, nope seems its requiem. Loaded with satin and no crash, just with requiem.

I do not crash at all. The resource pack force reloads infinitely. I had both satin and cardinal on.

**Comment by Syclusion** [comment]
> > Hmm wait, nope seems its requiem. Loaded with satin and no crash, just with requiem.
> 
> I do not crash at all. The resource pack force reloads infinitely. I had both satin and cardinal on.

Semantics, the resource stitching is failing from what it looks like. I also noticed you had create, remove it and see if I am wrong

**Comment by Syclusion** [comment]
Crash doesn't always mean a client crash (ergo the window closes) quilt or fabric especially

**Comment by lumithespoofy64** [comment]
> > > Hmm wait, nope seems its requiem. Loaded with satin and no crash, just with requiem.
> > 
> > 
> > I do not crash at all. The resource pack force reloads infinitely. I had both satin and cardinal on.
> 
> Semantics, the resource stitching is failing from what it looks like. I also noticed you had create, remove it and see if I am wrong

I have already tried doing that. Requiem alone fails.

**Comment by Syclusion** [comment]
Strange, requiem alone works for me

**Comment by lumithespoofy64** [comment]
> Strange, requiem alone works for me

I dont know what it is. I get Requiem, it trys to load, fails to load an obelisk. I just wanna throw the funny rat

**Comment by Syclusion** [comment]
> > Strange, requiem alone works for me
> 
> I dont know what it is. I get Requiem, it trys to load, fails to load an obelisk. I just wanna throw the funny rat

Send log

**Comment by Syclusion** [comment]
Without create

**Comment by lumithespoofy64** [comment]
> > > Strange, requiem alone works for me
> > 
> > 
> > I dont know what it is. I get Requiem, it trys to load, fails to load an obelisk. I just wanna throw the funny rat
> 
> Send log

I am unable to. Im on a car ride home.

**Comment by Syclusion** [comment]
> > > > Strange, requiem alone works for me
> > > 
> > > 
> > > I dont know what it is. I get Requiem, it trys to load, fails to load an obelisk. I just wanna throw the funny rat
> > 
> > 
> > Send log
> 
> I am unable to. Im on a car ride home.

Then how did you try it without create? I only ask because that sounds like the error I was running into with it.

**Comment by lumithespoofy64** [comment]
> > > > > Strange, requiem alone works for me
> > > > 
> > > > 
> > > > I dont know what it is. I get Requiem, it trys to load, fails to load an obelisk. I just wanna throw the funny rat
> > > 
> > > 
> > > Send log
> > 
> > 
> > I am unable to. Im on a car ride home.
> 
> Then how did you try it without create? I only ask because that sounds like the error I was running into with it.

I tried it beforehand to troubleshoot to see if it was requiem. It was.

**Comment by Syclusion** [comment]
> > > > > > Strange, requiem alone works for me
> > > > > 
> > > > > 
> > > > > I dont know what it is. I get Requiem, it trys to load, fails to load an obelisk. I just wanna throw the funny rat
> > > > 
> > > > 
> > > > Send log
> > > 
> > > 
> > > I am unable to. Im on a car ride home.
> > 
> > 
> > Then how did you try it without create? I only ask because that sounds like the error I was running into with it.
> 
> I tried it beforehand to troubleshoot to see if it was requiem. It was.

That wasn't my question, i believe it's an incompatibility between requiem and create. You must have misunderstood me when I said try it without create to verify if I was correct. Requiem alone does not crash.

**Comment by lumithespoofy64** [comment]
> > > > > > > Strange, requiem alone works for me
> > > > > > 
> > > > > > 
> > > > > > I dont know what it is. I get Requiem, it trys to load, fails to load an obelisk. I just wanna throw the funny rat
> > > > > 
> > > > > 
> > > > > Send log
> > > > 
> > > > 
> > > > I am unable to. Im on a car ride home.
> > > 
> > > 
> > > Then how did you try it without create? I only ask because that sounds like the error I was running into with it.
> > 
> > 
> > I tried it beforehand to troubleshoot to see if it was requiem. It was.
> 
> That wasn't my question, i believe it's an incompatibility between requiem and create. You must have misunderstood me when I said try it without create to verify if I was correct. Requiem alone does not crash.

It does on my pc for whatever reason. I use modrinth on Win10. Im just going to mark this as unsolved.
