### ISSUE TITLE
Mod uses baritone? How do i get the mindless corpses to walk then?

### ISSUE THREAD

**Issue by walksanatora** [Ladysnake/Requiem#671]
How do I command them to do thy bidding

**Comment by Xiribidus** [comment]
You don't, you can only keep backup bodies
https://ladysnake.org/wiki/requiem/gameplay#becoming-human-again

**Comment by walksanatora** [comment]
then why does the shell have a pathfinding process
https://github.com/Ladysnake/Requiem/blob/1.20/src/main/java/ladysnake/requiem/common/entity/ai/ShellPathfindingProcess.java

**Comment by Pyrofab** [comment]
Yeah it's all unfinished. You can technically run commands on them to make them do things, but right now there is nothing in the base mod to make them act.
