### ISSUE TITLE
(beta17) Big Globe 4.4.1 multiplayer issues causes weird shell bug(s)

### ISSUE THREAD

**Issue by ghotiPhoti** [Ladysnake/Requiem#673]
upon closer inspection it's an error caused by the newest version of Big Globe, but I thought these errors would be worth documenting regardless.

When running the latest version of the Big Globe worldgen mod with Requiem, this message appears every time someone attempts to dissociate. commands that cause the creation of a player shell also fail, giving an ambiguous "An unexpected error occured trying to execute that command." error in chat/log.

> [18:08:19] [Render thread/WARN]: Ignoring player info update for unknown player 8e4ba489-ac9d-4bfd-94f8-68b9f634d59e
> [18:08:19] [Server thread/ERROR]: Error executing task on Server
> net.minecraft.class_148: Saving entity NBT
> 	at net.minecraft.class_1297.method_5647(class_1297.java:1844) ~[minecraft-1.20.1.i0:0/:?]
> 	at ladysnake.requiem.common.remnant.PlayerSplitter.performNbtCopy(PlayerSplitter.java:240) ~[requiem-2.0.0-beta.17.i0:0/:?]
> 	at ladysnake.requiem.common.entity.PlayerShellEntity.storePlayerData(PlayerShellEntity.java:150) ~[requiem-2.0.0-beta.17.i0:0/:?]
> 	at ladysnake.requiem.common.remnant.PlayerSplitter.createShell(PlayerSplitter.java:111) ~[requiem-2.0.0-beta.17.i0:0/:?]
> 	at ladysnake.requiem.common.remnant.PlayerSplitter.doSplit(PlayerSplitter.java:80) ~[requiem-2.0.0-beta.17.i0:0/:?]
> 	at ladysnake.requiem.common.remnant.RemnantComponentImpl.splitPlayer(RemnantComponentImpl.java:185) ~[requiem-2.0.0-beta.17.i0:0/:?]
> 	at ladysnake.requiem.common.VanillaRequiemPlugin.lambda$onRequiemInitialize$4(VanillaRequiemPlugin.java:194) ~[requiem-2.0.0-beta.17.i0:0/:?]
> 	at ladysnake.requiem.api.v1.event.requiem.InitiateFractureCallback.lambda$static$0(InitiateFractureCallback.java:31) ~[requiem-api-2.0.0-beta.17.i0:0/:?]
> 	at ladysnake.requiem.common.network.ServerMessageHandling.lambda$init$4(ServerMessageHandling.java:78) ~[requiem-2.0.0-beta.17.i0:0/:?]
> 	at net.minecraft.class_3738.run(class_3738.java:18) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-1.20.1.i0:0/:?]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.lang.NullPointerException: Cannot read field "entrance" because "this.bigglobe_waypoints" is null
> 	at net.minecraft.class_1657.handler$chm000$bigglobe$saveHyperspaceEntrance(class_1657.java:6405) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.class_1657.method_5652(class_1657.java:874) ~[minecraft-1.20.1.i0:0/:?]
> 	at net.minecraft.class_3222.method_5652(class_3222.java:362) ~[minecraft-1.20.1.i0:0/:?]
> 	at baritone.api.fakeplayer.FakeServerPlayerEntity.method_5652(FakeServerPlayerEntity.java:227) ~[automatone-0.11.0.i0:0/:0.11.0]
> 	at ladysnake.requiem.common.entity.PlayerShellEntity.method_5652(PlayerShellEntity.java:286) ~[requiem-2.0.0-beta.17.i0:0/:?]
> 	at net.minecraft.class_1297.method_5647(class_1297.java:1826) ~[minecraft-1.20.1.i0:0/:?]
> 	... 21 more

also worth noting that while shells were failing to be created regardless of worldtype, players were able to join if the worldtype was Default.

modlist for test
- Big Globe-4.4.1-MC1.20.1.jar
- indium-1.0.34+mc1.20.1.jar
- lithium-fabric-mc1.20.1-0.11.2.jar
- qfapi-7.6.0_qsl-6.2.0_fapi-0.92.2_mc-1.20.1.jar
- requiem-2.0.0-beta.17.jar
- satin-1.14.0.jar
- sodium-fabric-0.5.11+mc1.20.1.jar
- starlight-1.1.2+fabric.dbc156f.jar

a few other performance/library mods were included too but were disabled during testing:
- architectury-9.2.14-fabric
- c2me-fabric-mc1.20.1-0.2.0+alpha.11.13
- cloth-config-11.1.136-fabric
- ferritecore-6.0.1-fabric
- iris-1.7.2+mc1.20.1
- modmenu-7.2.2
- RoughlyEnoughItems-12.1.780-fabric

**Comment by ghotiPhoti** [comment]
the problem's Quilt affecting Big Globe. https://github.com/Builderb0y/BigGlobe/issues/31
this should probably be closed.

**Comment by Builderb0y** [comment]
The stack trace posted here was actually my bug. I did not anticipate mods adding new player-like entity classes. I'll fix it in the next version. But yeah, this issue can be closed now.
