### ISSUE TITLE
Interactions with Tough as Nails

### ISSUE THREAD

**Issue by wenlfs** [Ladysnake/Requiem#72]
Some features from Tough as Nais are active but doesn't have any effect.

The temperature bar is active when the player is a soul or is possessing something and isn't reseted (if it should since is a different body) when the player possesses some entity. The player never get hipo or hyperthermia.

The thirsty bar is displayed when in an undead body. It is displayed but doesn't decrease.

Personally, I think it's right they don't work beacuse I just think that they should be hided too. Hope you agree and it can be solved in your side.

Thank you anyways. I really love your mod

**Comment by Pyrofab** [comment]
Tough as Nails is not on a supported version anymore, so I'll close this for now.
