### ISSUE TITLE
Compatibility with Mob Amputation

### ISSUE THREAD

**Issue by wenlfs** [Ladysnake/Requiem#73]
Odd behaviors when possessing an undead:
- [x] Can't break blocks;
- [x] You recive sufocation damage in closed spaces (two blocks heigh usualy) or near walls sometimes;
- [x] Jump to higher blocks (also when trying to get out of water) almost ever results in visual glitch;
- [x] Attack almost never works and the same goes to break things like grass;
- [x] The player can't pickup items using custom pickup- This happen to me cause I use ItemPhysic;

Aside it, would also be possible to add some compatibility to when the mob is decaptated? Because when you are possessing some mob and it is decaptated it should die but it doesn't happen. And if you want to add some compatibility to arms dismemberment too, go ahead.

Link to mod page: https://minecraft.curseforge.com/projects/mob-amputation

If those aren't not to be solved by you, sorry. Thank you for read.

**Comment by Pyrofab** [comment]
All of these issues are fixed in Requiem, with the exception of mob amputation compat. But the latter is currently not available on a supported version.
