### ISSUE TITLE
Incompatibility with SpongeForge

### ISSUE THREAD

**Issue by Azvalk** [Ladysnake/Requiem#78]
SpongeForge add a thing, sponge:human ( you see it if you remove sponge from your server, it ask a /fml confirm to remove this sponge:human

Because of that thing, we can't enter in any monster.
( no error, no log )
So.. It's impossible to play with Dissolution on a sponge forge server ^^'
Please make a compatibility thing if you can, good luck :D

**Comment by Pyrofab** [comment]
how the what

**Comment by Pyrofab** [comment]
Technically fixed by virtue of Sponge not having a 1.14.4 version !
