### ISSUE TITLE
Undead mounts

### ISSUE THREAD

**Issue by Jomik** [Ladysnake/Requiem#83]
As discussed in Discord. 
I feel like it would be a cool addition to allow us to mount mobs that we see the undead mounted on.

That is especially zombie and skeleton horses, to allow us to actually travel at decent speeds if we manage to find one.
But it would also be cool if we could mount spiders, as a skeleton, or chickens as a baby undead. And make use of their wall climbing or gliding traits.

**Comment by Pyrofab** [comment]
Yes, added in Requiem !
